# Packages:

import re
from pymongo import MongoClient
from bs4 import BeautifulSoup
import dateparser
import requests
import pandas as pd
from pymongo import MongoClient
from urllib.parse import urlparse
from datetime import datetime
from dateutil.relativedelta import relativedelta
from pymongo.errors import DuplicateKeyError
from pymongo.errors import CursorNotFound
# from peacemachine.helpers import urlFilter
from newsplease import NewsPlease

# db connection:
db = MongoClient('mongodb://zungru:balsas.rial.tanoaks.schmoe.coffing@db-wibbels.sas.upenn.edu/?authSource=ml4p&tls=true').ml4p

text = """
Post Sitemap

Generated by All in One SEO, this is an XML Sitemap, meant to be consumed by search engines like Google or Bing.

You can find more information about XML Sitemaps at sitemaps.org.

This sitemap contains 1000 URLs and was generated on October 3, 2024 at 8:57 PM

HomeSitemap IndexPost Sitemap
URL
https://www.jamhurimedia.co.tz/wanawake-watano-wafanyiwa-upasuaji-kupitia-matundu-madogo/

https://www.jamhurimedia.co.tz/fcf-kutumia-bil-1-2-kusaidia-miradi-ya-maendeleo-na-kutoa-chakula-shuleni/

https://www.jamhurimedia.co.tz/tma-yatabiri-upepo-mkali-unaofikia-kilomita-40-kwa-saa/

https://www.jamhurimedia.co.tz/tanzania-yafungua-rasmi-ubalozi-wake-jijini-jakarta-indonesia/

https://www.jamhurimedia.co.tz/fichua-wakwepa-kodiupate-asilimia-tatu/

https://www.jamhurimedia.co.tz/kofih-yadhamiria-kupunguza-vifo-vya-uzazi-na-watoto-wachanga-pwani/

https://www.jamhurimedia.co.tz/rc-mara-ataka-halmashauri-tarime-vijijini-kutumia-pesa-za-mapato-ya-ndani-kumalizia-viporo-vya-miradi/

https://www.jamhurimedia.co.tz/jaji-mahakama-ya-afrika-asisitiza-usawa-kijinsia/

https://www.jamhurimedia.co.tz/mtaturu-akemea-tabia-ya-watu-wanaoita-wenzao-chawa/

https://www.jamhurimedia.co.tz/gazeti-la-jamhuri-la-juni-20-26-2023/

https://www.jamhurimedia.co.tz/rc-ruvuma-atoa-maagizo-20-kwa-halmashauri-mbili-zilizopata-hati-zenye-mashaka/

https://www.jamhurimedia.co.tz/abiria-watano-wa-basi-la-newforce-wafariki-njombe/

https://www.jamhurimedia.co.tz/chongolo-aendelea-na-ziara-bahi-mkoani-dodoma/

https://www.jamhurimedia.co.tz/kinana-akutana-na-balozi-wa-brazil-nchini/

https://www.jamhurimedia.co.tz/wamteka-mtoto-na-kutaka-walipwe-mil-50/

https://www.jamhurimedia.co.tz/tanzania-kufungua-rasmi-ofisi-za-ubalozi-indonesia/

https://www.jamhurimedia.co.tz/serikali-kuangalia-upya-ajira-za-walimu/

https://www.jamhurimedia.co.tz/majaliwahatutadharau-maoni-ushauri-kuhusu-uwekezaji-bandari/

https://www.jamhurimedia.co.tz/shirika-la-stemm-lafanikisha-kambi-ya-huduma-ya-afya-bure-singida/

https://www.jamhurimedia.co.tz/jk-awapongeza-ali-kibambwana-samatta-awapa-ushauri/

https://www.jamhurimedia.co.tz/kundo-serikali-kutoa-mafunzo-kwa-wataalam-wa-tehama-zaidi-ya-500/

https://www.jamhurimedia.co.tz/waajiri-watakiwa-kuwasilisha-taarifa-za-wastaafu-mapema-kuwaondolea-usumbufu/

https://www.jamhurimedia.co.tz/jaji-maghimbi-mrundikano-wa-mashauri-dar-kuwa-historia/

https://www.jamhurimedia.co.tz/act-wazalendo-yavuna-wanachma-wa-chadema/

https://www.jamhurimedia.co.tz/rostam-mjadala-kuhusu-bandari-ya-dar-es-salaam-na-dp-world-unaendeshwa-kishabiki/

https://www.jamhurimedia.co.tz/msd-yaanza-rasmi-zoezi-la-kuhesabu-mali/

https://www.jamhurimedia.co.tz/waziri-mabula-awatuliza-wapangaji-kariakoo/

https://www.jamhurimedia.co.tz/bot-shilingi-ya-tanzania-ndiyo-fedha-pekee-ambayo-inaruhusiwa-kutumika-nchini/

https://www.jamhurimedia.co.tz/wajumbe-cwt-waiomba-serikali-kuingilia-kati-mgogoro-ndani-ya-chama-hicho/

https://www.jamhurimedia.co.tz/rc-kunenge-aagiza-halmashauri-rufiji-kuandaa-mipango-kwa-kuzingatia-vipaombele/

https://www.jamhurimedia.co.tz/watendaji-waaswa-kusimamia-ugawaji-rasilimali-za-taifa/

https://www.jamhurimedia.co.tz/mwonekano-gazeti-la-jamhuri-juni-20-26-2023/

https://www.jamhurimedia.co.tz/baobab-queens-kuwa-timu-ya-wanawake-ya-azam-fc/

https://www.jamhurimedia.co.tz/watu-100-wamekufa-nchini-india-kutokana-na-joto-kali/

https://www.jamhurimedia.co.tz/ruvuma-ilivyofanikiwa-kutoa-chanjo-kwa-zaidi-ya-asilimia-10/

https://www.jamhurimedia.co.tz/taifa-stars-yafufua-matumaini-afcon-2023/

https://www.jamhurimedia.co.tz/tanzanite-yaibuka-ushindi-wa-vikapu-69-34-dhidi-ya-timu-ya-taifa-ya-eritrea/

https://www.jamhurimedia.co.tz/polisi-marufuku-kuandamana-jumatatu/

https://www.jamhurimedia.co.tz/rc-tabora-atoa-siku-saba-kampuni-ya-tumbaku-kulipa-wakulima-bil-20/

https://www.jamhurimedia.co.tz/rais-samia-apokea-gawio-la-bil-45-4-kutoka-nmb/

https://www.jamhurimedia.co.tz/utabiri-wa-hali-ya-hewa-kwa-saa-24-zijazo-5/

https://www.jamhurimedia.co.tz/chongolo-tukichezea-vyanzo-vya-maji-tunachezea-uhai-wetu/

https://www.jamhurimedia.co.tz/tanroads-yaweka-historia-yasaini-mikataba-saba-ya-trillion-3-7/

https://www.jamhurimedia.co.tz/polisi-arusha-wakamata-ngombe-319-walioibiwa/

https://www.jamhurimedia.co.tz/rais-samia-awaapisha-mabalozi-na-manaibu-katibu-wakuu-dodoma/

https://www.jamhurimedia.co.tz/polepole-awasilisha-hati-za-utambulisho-kwa-rais-wa-cuba/

https://www.jamhurimedia.co.tz/ndumbaro-atatua-mgogoro-uliodumu-kwa-miaka-nane-shinyanga/

https://www.jamhurimedia.co.tz/serikali-yatenga-bil-5-kugharamia-huduma-za-kibingwa/

https://www.jamhurimedia.co.tz/wakulima-wa-ufuta-tunduru-waingiza-bil-10-5-kupitia-mfumo-wa-stakabadhi-ghalani/

https://www.jamhurimedia.co.tz/bajeti-kuu-ya-serikali-yawasilishwa-bungeni/

https://www.jamhurimedia.co.tz/vifo-vya-uzazi-kwa-mama-na-mtoto-vyapungua-pwani/

https://www.jamhurimedia.co.tz/rais-dkt-mwinyi-azungumza-na-ujumbe-wa-unesco/

https://www.jamhurimedia.co.tz/akiba-ya-fedha-za-kigeni-inaridhisha/

https://www.jamhurimedia.co.tz/dkt-mwigulu-nchemba-akionesha-bajeti-kuu-ya-serikali/

https://www.jamhurimedia.co.tz/watendaji-watakiwa-kutoa-fursa-kwa-wamiliki-wa-ardhi-kwa-wawekezaji/

https://www.jamhurimedia.co.tz/muhimbili-namibia-kushirikiana-kujenga-uwezo-wa-utoaji-huduma-za-kibingwa/

https://www.jamhurimedia.co.tz/rais-ateta-na-washauri-wake/

https://www.jamhurimedia.co.tz/tma-yatoa-utabiri-wa-hali-ya-hewa-kwa-saa-24-zijazo/

https://www.jamhurimedia.co.tz/chongolo-afunguka-sakata-la-bandari/

https://www.jamhurimedia.co.tz/miradi-293-yasajiliwa-na-kuongeza-uwekezaji-nchini/

https://www.jamhurimedia.co.tz/serikali-yaeleza-sababu-zilizosababisha-mfumuko-wa-bei-nchini/

https://www.jamhurimedia.co.tz/wadau-eiti-wajadili-fursa-mbalimbali-za-madini/

https://www.jamhurimedia.co.tz/matkio-katika-picha-waziri-mkuu-bungeni/

https://www.jamhurimedia.co.tz/dkt-chemba-awasilisha-taarifa-hali-ya-uchumi-na-mpango-wa-maendeleo-wa-taifa-2023-2024/

https://www.jamhurimedia.co.tz/tanzania-yawakaribisha-wawekezaji-kutoka-urusi/

https://www.jamhurimedia.co.tz/hospitali-ya-muhimbili-mlogazila-yawawekea-puto-wagonjwa-87/

https://www.jamhurimedia.co.tz/mpango-afanya-mazungumzo-na-mkuu-wa-taasisi-ya-korea-ya-bahari/

https://www.jamhurimedia.co.tz/serikali-yaendeleza-mapambano-dhidi-ya-magugu-maji-ziwa-victoria/

https://www.jamhurimedia.co.tz/museveni-apimwa-na-kukutwa-tena-na-virusi-vya-corona/

https://www.jamhurimedia.co.tz/simbachawane-alitaka-e-ga-kuimarisha-kituo-chake-cha-utafiti-kuongeza-ubunifu-wa-tehama/

https://www.jamhurimedia.co.tz/rais-samia-vitega-uchumi-kama-hivi-vitaongeza-tija-kwa-nssf/

https://www.jamhurimedia.co.tz/madaktari-uingereza-waanza-mgomo-wa-siku-3/

https://www.jamhurimedia.co.tz/wananchi-kupatiwa-matibabu-ya-dharura-hospitali-ya-nyanghwale/

https://www.jamhurimedia.co.tz/wawili-wapandikizwa-uume-benjamini-mkapa/

https://www.jamhurimedia.co.tz/nabi-bye-bye-yanga/

https://www.jamhurimedia.co.tz/gazeti-la-jamhuri-juni-13-19-2023/

https://www.jamhurimedia.co.tz/kigongo-busisi-kuvukwa-dakika-4-daraja-litakapokamilika/

https://www.jamhurimedia.co.tz/watu-79-wafariki-katika-ajali-ya-boti-ugiriki/

https://www.jamhurimedia.co.tz/rais-samia-akagua-ujenzi-wa-meli-mpya-ya-abiria-na-mizigo-ya-mv-mwanza/

https://www.jamhurimedia.co.tz/halmashauri-songea-yapokea-bilioni-tatu-kutekeleza-miradi-ya-elimu/

https://www.jamhurimedia.co.tz/fountain-gate-yainunua-singida-big-stars/

https://www.jamhurimedia.co.tz/siku-ya-mchangiaji-damu-yanga-yachangia-chupa-za-damu-627/

https://www.jamhurimedia.co.tz/uvccm-zanzibar-yamshauri-msajili-kukifuta-chama-cha-act-wazalendo/

https://www.jamhurimedia.co.tz/serikali-kujenga-kiwanja-kipya-cha-michezo-jijini-arusha/

https://www.jamhurimedia.co.tz/mnh-yawezesha-uanzishwaji-wa-kliniki-ya-himofili-na-selimundu-kigoma/

https://www.jamhurimedia.co.tz/rais-samia-atembelea-na-kukagua-daraja-la-jp-magufuli-kigongo-busisi-km-3/

https://www.jamhurimedia.co.tz/rais-samia-atembelea-na-kukagua-daraja-la-jp-magufuli/

https://www.jamhurimedia.co.tz/rais-samia-asalimiana-na-wananchi-buhongwa-akielekea-busisi-kukagua-daraja-la-magufuli/

https://www.jamhurimedia.co.tz/rais-samiaserikali-itajenga-maghala-ya-chakula-nchi-nzima/

https://www.jamhurimedia.co.tz/nec-yatangaza-uchaguzi-mdogo-wa-kata-14/

https://www.jamhurimedia.co.tz/rais-awateua-lukuvi-bulembo-kuwa-washauri-wake/

https://www.jamhurimedia.co.tz/ubungo-washirikiana-na-hananja-kongamano-la-kuchangia-damu-kwa-hiari/

https://www.jamhurimedia.co.tz/zaidi-ya-bil-230-zinavyotekeleza-miradi-ya-tanroad-ruvuma/

https://www.jamhurimedia.co.tz/jeshi-la-polisi-nchini-iaa-waandika-historia-mpya/

https://www.jamhurimedia.co.tz/taasisi-za-umma-zatakiwa-kuendesha-vikao-vyake-kwa-mfumo-wa-e-mkutano/

https://www.jamhurimedia.co.tz/othman-tumalize-migogoro-kwa-maslahi-ya-wananchi/

https://www.jamhurimedia.co.tz/ndalichako-aziagiza-halmashauri-kutenga-bajeti-ya-mafuta-kwa-wenye-ualbino/

https://www.jamhurimedia.co.tz/dkt-slaa-aunga-mkono-uwekezaji-aishauri-serikari-kurekebisha-dosari-mkataba-wa-dp-world/

https://www.jamhurimedia.co.tz/biteko-asisitiza-kukamilika-jengo-la-madini-wa-wakati-dodoma/

https://www.jamhurimedia.co.tz/kunenge-azindua-zahanati-kwenye-kituo-cha-yatima-kinachoendeshwa-na-anna-mkapa/

https://www.jamhurimedia.co.tz/rais-samia-afanya-uteuzi-mwingine-2/

https://www.jamhurimedia.co.tz/muuguzi-adaiwa-kubaka-mjamzito-hospitalini-tabora-uchunguzi-umekamilika/

https://www.jamhurimedia.co.tz/samia-atembelea-kituo-cha-utamaduni-na-makumbusho-ya-wasukuma-bujora/

https://www.jamhurimedia.co.tz/senyamule-aagiza-chemba-kujipanga-upya/

https://www.jamhurimedia.co.tz/tanzania-yazindua-ubalozi-wake-austria/

https://www.jamhurimedia.co.tz/marekani-yatenga-fedha-kupambana-na-ukimwi-nchini/

https://www.jamhurimedia.co.tz/rais-samia-azungumza-na-viongozi-wa-dini-mwanza/

https://www.jamhurimedia.co.tz/zanzibar-kunufaika-na-biashara-ya-kaboni/

https://www.jamhurimedia.co.tz/mwijuma-aikabidhi-yanga-kombe-la-shirikisho-la-azam-sports/

https://www.jamhurimedia.co.tz/gazeti-la-jamhuri-juni-13-19/

https://www.jamhurimedia.co.tz/waziri-mkuu-azindua-kongamano-la-kujengewa-uelewa-juu-ya-sauti-zilizozidi-viwango-katika-nyumba-za-ibada/

https://www.jamhurimedia.co.tz/timu-ya-taifa-ya-walemavu-wa-akilii-waenda-ujerumani-kushiriki-michezo-ya-dunia/

https://www.jamhurimedia.co.tz/majaliwa-aongoza-kongamano-la-viongozi-wa-dini-kuhusu-mazingira/

https://www.jamhurimedia.co.tz/katambi-mishahara-na-maslahi-ya-madereva-imeboreshwa/

https://www.jamhurimedia.co.tz/ruvuma-kuzindua-kampeni-ya-kitaifa-ya-msaada-wa-kisheria-ya-mama-samia/

https://www.jamhurimedia.co.tz/bei-ya-ufuta-lindi-yazidi-kupaa/

https://www.jamhurimedia.co.tz/miaka-40-jela-kwa-ujangili-meno-ya-tembo-lushoto/

https://www.jamhurimedia.co.tz/gazeti-la-jamhuri-juni-6-12-2023/

https://www.jamhurimedia.co.tz/shirika-la-akili-platform-tanzania-latoa-elimu-ya-kujitegemea-kwa-vijana/

https://www.jamhurimedia.co.tz/bunge-lapitisha-azimio-la-mkataba-wa-utendajikazi-wa-bandari/

https://www.jamhurimedia.co.tz/rais-samia-afanya-uteuzi-5/

https://www.jamhurimedia.co.tz/tanzaniazambia-kutatua-changamoto-za-usafirishaji-tunduma/

https://www.jamhurimedia.co.tz/chongolo-ateta-na-balozi-wa-china-nchini/

https://www.jamhurimedia.co.tz/picha-ya-waziri-mkuu-akiwa-bungeni/

https://www.jamhurimedia.co.tz/mawakili-wa-serikali-watakiwa-kutatua-migogoro-kwa-njia-ya-majadiliano/

https://www.jamhurimedia.co.tz/mashirika-waadhimisha-siku-ya-bahari-duniani/

https://www.jamhurimedia.co.tz/kibajaji-amjia-juu-mbowe/

https://www.jamhurimedia.co.tz/tanapa-yazitendea-haki-fedha-za-samia/

https://www.jamhurimedia.co.tz/bot-yatoa-angalizo-kwa-watumiaji-fedha-za-kigeni/

https://www.jamhurimedia.co.tz/tef-yashtushwa-na-kufungiwa-huduma-za-maudhui-mtandaoni-za-kampuni-ya-mwananchi/

https://www.jamhurimedia.co.tz/waziri-mkuu-afunga-mkutano-mkuu-wa-kumi-wa-wadau-wa-lishe/

https://www.jamhurimedia.co.tz/dk-tulia-ataka-ushirikiano-na-mawazo-bunifu-kuliendeleza-bara-la-afrika-na-watu-wake/

https://www.jamhurimedia.co.tz/rais-dk-samia-azungumza-na-rais-wa-samsung-ikulu-dar/

https://www.jamhurimedia.co.tz/yanga-wapata-screen-protector-mwingine/

https://www.jamhurimedia.co.tz/mahakama-yaridhia-mabaki-ya-maradona-kuhamishwa/

https://www.jamhurimedia.co.tz/hakuna-utekaji-wa-watoto-njombe-polisi/

https://www.jamhurimedia.co.tz/zungu-tuendelee-kumuunga-mkono-rais-samia-matumizi-ya-nishati-safi-ya-kupikia/

https://www.jamhurimedia.co.tz/waziri-kijaji-ataka-mto-tegeta-kusafishwa-kulinda-mazingira-na-kupunguza-athari/

https://www.jamhurimedia.co.tz/mathias-canal-ampa-maua-yake-mwigulu-achangia-mil-4-2-shule-ya-msingi-kiomboi/

https://www.jamhurimedia.co.tz/vijiji-vyote-mtwara-vimefikiwa-na-umeme-sasa-ni-zamu-ya-vitongoji-150/

https://www.jamhurimedia.co.tz/rc-kunenge-azitaka-taasisi-wezeshi-kuweka-mazingira-rafiki-kwa-wafanyabiashara-wadogo/

https://www.jamhurimedia.co.tz/lina-pg-tour-yamsogeza-mollel-karibu-na-dubai/

https://www.jamhurimedia.co.tz/uganda-yasaka-ufadhili-wa-kuzalisha-megawati-1600-za-umeme/

https://www.jamhurimedia.co.tz/israel-mashambulizi-ya-iran-ni-kitendo-kikubwa-cha-uchokozi/

https://www.jamhurimedia.co.tz/biden-marekani-haiungi-mkono-shambulio-la-israeli/

https://www.jamhurimedia.co.tz/rc-kunenge-awahimiza-wazee-kibaha-mji-kumtunza-na-kumlinda-rais-samia/

https://www.jamhurimedia.co.tz/dk-yonaz-hali-ya-chakula-nchini-inaendelea-kuimarika/

https://www.jamhurimedia.co.tz/wawili-wauawa-kwa-kunyongwa-na-kutobolewa-macho-tanga/

https://www.jamhurimedia.co.tz/bashe-atoa-saa-24-kwa-kampuni-ya-rv-kulipa-madeni-ya-wakulima/

https://www.jamhurimedia.co.tz/bashe-acharuka-ataka-mabadiliko-vyama-vya-ushirika/

https://www.jamhurimedia.co.tz/jkt-queens-yafanya-mauaji-ngao-ya-jamii/

https://www.jamhurimedia.co.tz/tanzania-kuandaa-mashindano-akili-mnemba/

https://www.jamhurimedia.co.tz/kongamano-la-10-la-jotoardhi-afrika-kufanyika-oktoba-21-dar/

https://www.jamhurimedia.co.tz/serikali-yawataka-wataalam-wa-maabara-za-binadamu-kulinda-taaluma-yao/

https://www.jamhurimedia.co.tz/tba-kuwaondoa-wadaiwa-sugu-648-wanaodaiwa-bilioni-14-8-kuanzia-oktoba-7-mwaka-huu/

https://www.jamhurimedia.co.tz/iran-yatishia-kushambulia-miundombinu-yote-ya-israeli/

https://www.jamhurimedia.co.tz/bei-ya-mafuta-yapanda-baada-ya-shambulizi-la-iran/

https://www.jamhurimedia.co.tz/who-afrika-ina-barabara-gari-chache-lakini-ajali-nyingi/

https://www.jamhurimedia.co.tz/wataalamu-wa-maabara-toeni-majibu-sahihi-kuwasaidia-watanzania-dk-biteko/

https://www.jamhurimedia.co.tz/tumieni-mifumo-rasmi-kuhifadhi-fedha-pinda/

https://www.jamhurimedia.co.tz/ajenda-ya-utunzaji-mazingira-iwe-ya-kudumu-waziri-chana/

https://www.jamhurimedia.co.tz/ifikapo-2030-korosho-zote-zitabanguliwa-nchini-bashe/

https://www.jamhurimedia.co.tz/nssf-yapiga-hatua-kubwa-kiutendaji-awataka-watanzania-kujiunga-na-mfuko-isiyo-rasmi/

https://www.jamhurimedia.co.tz/sekta-ya-viwanda-na-uwekezaji-yapaa-pwani/

https://www.jamhurimedia.co.tz/dc-malinyi-ahimiza-wananchi-uchaguzi-serikali-za-mitaa/

https://www.jamhurimedia.co.tz/brela-kuendesha-kampeni-ya-utoaji-elimu-kuhusu-urasimishwaji-kwa-wafanyabiashara/

https://www.jamhurimedia.co.tz/makusanyo-ya-tra-yapaa/

https://www.jamhurimedia.co.tz/iran-yaishambulia-israel-kwa-makombora-180/

https://www.jamhurimedia.co.tz/mbunge-viti-maalum-mariam-nyoka-aunga-mkono-jitihada-za-serikali-atoa-msaada-wa-mil-2-zahanati-ya-muhepai/

https://www.jamhurimedia.co.tz/mathias-canal-achangia-mil-5-kupunguza-changamoto-zinazoikabili-shule-ya-msingi-tutu-iramba/

https://www.jamhurimedia.co.tz/dk-kisenge-uvutaji-wa-sigara-na-unywaji-wa-pombe-ni-hatari-kwa-mjamzito/

https://www.jamhurimedia.co.tz/serikali-kujenga-kongani-ya-viwanda-vya-kuchakata-mazao-mikoa-ya-kusini/

https://www.jamhurimedia.co.tz/tamasha-la-mitindo-nchini-labeba-taswira-mpya/

https://www.jamhurimedia.co.tz/mbwana-samatta-arejeshwa-taifa-stars/

https://www.jamhurimedia.co.tz/viongozi-vyama-vya-michezo-waaswa-kiwasilisha-hesabu-za-fedha-kwa-msajili-bmt/

https://www.jamhurimedia.co.tz/nishati-safi-ya-kupikia-italeta-mageuzi-makubwa-ulindaji-wa-mazingira-mahundi/

https://www.jamhurimedia.co.tz/jkci-yaanza-kutoa-huduma-ya-upimaji-wa-magonjwa-ya-moyo-bure-geita/

https://www.jamhurimedia.co.tz/russia-yaongeza-ukubwa-wa-jeshi-lake-hadi-milioni-1-5-kwenye-mipaka-yake/

https://www.jamhurimedia.co.tz/rea-kushiriki-samia-kilimo-biashara-expo-2024-morogoro/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-oktoba-7-2024/

https://www.jamhurimedia.co.tz/kuhifadhi-mbegu-za-uzazi-sh-milioni-moja/

https://www.jamhurimedia.co.tz/rais-samia-azindua-kitabu-cha-sokoine/

https://www.jamhurimedia.co.tz/bashe-atuma-salamu-kwa-wafanyabiashara-wanaowanyonya-wakulima-wa-korosho-mtwara/

https://www.jamhurimedia.co.tz/mtoto-mtanzania-ashinda-tuzo-ya-ballon-dor/

https://www.jamhurimedia.co.tz/utekelezaji-miradi-ya-maendeleo-uzingatie-vipaumbele-vya-wananchi-kapinga/

https://www.jamhurimedia.co.tz/urusi-yaushambulia-mji-wa-kiev-kwa-droni/

https://www.jamhurimedia.co.tz/mayele-afunguka-kurudi-tena-yanga/

https://www.jamhurimedia.co.tz/takukuru-yatoa-uzoefu-kimataifa/

https://www.jamhurimedia.co.tz/jkci-yaendelea-kuishangaza-dunia-kwa-matibabu-ya-kibingwa-ya-moyo/

https://www.jamhurimedia.co.tz/hezbollah-yathibitisha-kifo-cha-kiongozi-wake-nasrallah/

https://www.jamhurimedia.co.tz/waziri-ridhiwani-aongoza-kampeni-ya-kukabiliana-na-afya-ya-akili/

https://www.jamhurimedia.co.tz/rais-dk-samia-afunga-kikao-maalum-cha-uwt-taifa-bombambili-songea/

https://www.jamhurimedia.co.tz/lina-pg-tour-yafufua-gofu-moshi/

https://www.jamhurimedia.co.tz/rais-samia-azungumza-na-wanafunzi-wazazi-baada-ya-kuzindua-sekondari-ya-wasichana-namtumbo/

https://www.jamhurimedia.co.tz/wakati-umefika-wa-afrika-kubadilika-kwa-kutumia-nishati-safi-ya-kupikia-rais-samia/

https://www.jamhurimedia.co.tz/waendesha-baiskeki-kumuenzi-mwalimu-nyerere/

https://www.jamhurimedia.co.tz/wwf-wakutana-na-wadau-kujadili-na-kuboresha-utekelezaji-wa-uhifadhi-bioanuai/

https://www.jamhurimedia.co.tz/mkuu-wa-majeshi-ya-ulinzi-tanzania-atembelea-msumbiji/

https://www.jamhurimedia.co.tz/naibu-waziri-kigahe-azindua-maonyesho-ya-nishati-dar/

https://www.jamhurimedia.co.tz/biden-awaalika-viongozi-wa-dunia-kwenye-mkutano-kuhusu-ukraine/

https://www.jamhurimedia.co.tz/palestina-acheni-kuipatia-israel-silaha/

https://www.jamhurimedia.co.tz/papa-francis-akosoa-kuibuka-tena-kwa-vita/

https://www.jamhurimedia.co.tz/serikali-yatoa-trekta-tano-kwa-wanaotekeleza-mradi-wa-nbt-njombe/

https://www.jamhurimedia.co.tz/rais-samia-aagiza-kufufuliwa-kiwanda-cha-korosho-tunduru/

https://www.jamhurimedia.co.tz/serikali-yaahidi-kutumia-ndege-nyuki-kuwaondoa-tembo-kwenye-makazi-ya-watu-tunduru/

https://www.jamhurimedia.co.tz/mfumo-wa-kidigitali-wa-airpay-na-zeea-kuwarahisishia-wajasirimali-kupata-mikopo-kwa-urahisi/

https://www.jamhurimedia.co.tz/watumiaji-wa-mtandao-wa-airtel-kunufaika-na-huduma-mpya/

https://www.jamhurimedia.co.tz/mikoa-halmashauri-zaagizwa-kushiriki-maonesho-ya-viwanda/

https://www.jamhurimedia.co.tz/rais-dkt-samia-azungumza-na-wananchi-wa-mchomoro-namtumbo-mkoani-ruvuma/

https://www.jamhurimedia.co.tz/wenye-sifa-na-miaka-21-wajitokeze-uchaguzi-serikali-za-mitaa-dk-shemwelekwa/

https://www.jamhurimedia.co.tz/hakimu-wakili-wa-serikali-wakerwa-wakili-chuwa-kuchelesha-kesi/

https://www.jamhurimedia.co.tz/duwasa-yajenga-tenki-la-maji-la-lita-200000-nala-dodoma/

https://www.jamhurimedia.co.tz/rais-samia-aipongeza-afdb-utekelezaji-miundombinu-ya-barabara-nchini/

https://www.jamhurimedia.co.tz/rais-samia-awahimiza-wananchi-namtumbo-kuchagua-viongozi-serikali-ya-mtaa-wenye-sifa/

https://www.jamhurimedia.co.tz/mramba-azikaribisha-kampuni-za-uingereza-kuwekeza-kwenye-nishati-jadidifu/

https://www.jamhurimedia.co.tz/kikwete-apokea-msaada-wa-vifaa-tiba-na-madawati-nmb/

https://www.jamhurimedia.co.tz/rais-samia-ateua-wenyeviti-wa-bodi-mbalimbali/

https://www.jamhurimedia.co.tz/serikali-zanzibar-kujenga-uwanja-mkubwa-michezo-utakaokubalika-na-fifa-caf/

https://www.jamhurimedia.co.tz/rais-samia-ahutubia-wakazi-wa-nyasa-mkoani-ruvuma/

https://www.jamhurimedia.co.tz/rais-samia-afungua-barabara-mpya-ya-kiwango-cha-lami-ya-mbinga-mbamba-bay-ruvuma/

https://www.jamhurimedia.co.tz/rais-dkt-samia-aweka-jiwe-la-msingi-la-ujenzi-bandari-mpya-ya-mbamba-bay/

https://www.jamhurimedia.co.tz/kapombe-afunguka-alichoambiwa-na-mshambuliaji-wa-al-ahly-tripoli/

https://www.jamhurimedia.co.tz/ligi-ya-wavu-kurejea-septemba-27/

https://www.jamhurimedia.co.tz/jkci-yaendelea-kuwa-kivutio-utalii-tiba-afrika/

https://www.jamhurimedia.co.tz/samia-afungua-jengo-la-halmashauri-ya-mbinga-vijijini-awapongeza-viongozi-kwa-usimamizi/

https://www.jamhurimedia.co.tz/dk-biteko-azitaa-wizara-taasisi-na-wakala-serikalini-kutenga-bajeti-ya-kutosha-shimiwi/

https://www.jamhurimedia.co.tz/rea-kusambaza-umeme-vitongoji-135-mkoani-pwani-kunenge-amshukuru-rais-samia/

https://www.jamhurimedia.co.tz/bilioni-15-kusambaza-umeme-vitongojini-pwani/

https://www.jamhurimedia.co.tz/rais-dk-samia-afungua-jengo-la-ofisi-ya-mkurugenzi-mtendaji-wa-halmashauri-ya-wilaya-ya-mbinga/

https://www.jamhurimedia.co.tz/ruto-ataka-dunia-iwekeze-kwenye-nishati-salama-afrika/

https://www.jamhurimedia.co.tz/ulimwengu-wataka-mashariki-ya-kati-isitumbukie-vitani/

https://www.jamhurimedia.co.tz/serikali-ya-tanzania-kushiriki-kongamano-la-kimataifa-la-usafirishaji-nchini-china/

https://www.jamhurimedia.co.tz/marekani-iran-inataka-kumuua-trump/

https://www.jamhurimedia.co.tz/wasafirishaji-binadamu-wakamatwa/

https://www.jamhurimedia.co.tz/rais-samia-ashuhudia-usafishaji-kahawa-katika-kampuni-ya-aviv/

https://www.jamhurimedia.co.tz/p-didy-aomba-kuzungumza-na-watoto-wake/

https://www.jamhurimedia.co.tz/kapinga-mkakati-wa-matumizi-ya-maji-kwa-kuzingatia-mahitaji-ya-kila-sekta-umeleta-mafanikio/

https://www.jamhurimedia.co.tz/rais-samia-atembelea-kanisa-la-mt-benedicto-parokia-ya-peramiho-azungumza-na-watawa/

https://www.jamhurimedia.co.tz/rais-samia-afungua-ujenzi-wa-ghala-la-nafaka-luhimba/

https://www.jamhurimedia.co.tz/ubalozi-wa-saudi-arabia-waahidi-kudumisha-uhusiano-zaidi-na-tanzania/

https://www.jamhurimedia.co.tz/rais-samia-uzalishaji-kahawa-waongezeka-waingiza-dola-milioni-250/

https://www.jamhurimedia.co.tz/shambulizi-la-urusi-nchini-ukraine-lakatiza-huduma-za-umeme/

https://www.jamhurimedia.co.tz/meli-ya-kivita-ya-misri-yapeleka-silaha-somalia/

https://www.jamhurimedia.co.tz/rais-samia-afungua-shule-ya-msingi-mchepuo-wa-kiingereza-ya-chief-zulu-songea/

https://www.jamhurimedia.co.tz/rais-samia-aweka-jiwe-la-msingi-ujenzi-wa-maghala-28-ya-kuhifadhi-chakula-luhimba-ruvuma/

https://www.jamhurimedia.co.tz/polisi-wachunguza-kifo-cha-sonii-aliyefariki-wakati-akitoroshwa-mikononi-mwa-polisi-arusha/

https://www.jamhurimedia.co.tz/serikali-yaipongeza-green-acres-kwa-kuendelea-kufanya-vizuri-kitaaluma/

https://www.jamhurimedia.co.tz/samia-atoa-miezi-mitatu-mradi-wa-maji-mchangombole-madaba-kukamiika-songea/

https://www.jamhurimedia.co.tz/jkci-kutanua-huduma-za-matibabu-ya-moyo-nchini/

https://www.jamhurimedia.co.tz/rais-dkt-samia-atoa-miezi-mitatu-mradi-wa-maji-mtyangimbole-uanze-kufanya-kazi/

https://www.jamhurimedia.co.tz/watano-kizimbani-wakijifanya-wakala-wa-kampuni-za-simu-na-kuibia-watu-dar/

https://www.jamhurimedia.co.tz/mashambulizi-israel-yaua-watu-490/

https://www.jamhurimedia.co.tz/mwangesi-hauwezi-kuwa-mwangalizi-wa-maadili-ya-watu-wengine-kama-wewe-huna-maadili/

https://www.jamhurimedia.co.tz/tunazikaribisha-ngangari-ngunguri-na-nginjangija/

https://www.jamhurimedia.co.tz/tumeridhia-matapeli-wa-kiroho-waliangamize-taifa/

https://www.jamhurimedia.co.tz/tuunge-mkono-kwa-vitendo-mkakati-wa-taifa-wa-nishati-safi-ya-kupikia-katimba/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-septeba-24-302024/

https://www.jamhurimedia.co.tz/rais-samia-awaenzi-mashujaa-wa-vita-ya-majimaji/

https://www.jamhurimedia.co.tz/rais-samia-amtembelea-askofu-mkuu-jimbo-kuu-katoliki-songea/

https://www.jamhurimedia.co.tz/rais-mwinyi-smz-kuleta-mageuzi-katika-sekta-ya-elimu/

https://www.jamhurimedia.co.tz/rais-samia-aitaka-wizara-kushirikisha-wadau-kupendekeza-namna-bora-ya-kushughulikia-mmomonyoko-wa-maadili/

https://www.jamhurimedia.co.tz/naibu-kadhi-mkuu-ampongeza-shiraz-kwa-kujenga-msikiti-dar/

https://www.jamhurimedia.co.tz/dk-biteko-akutana-na-ujumbe-wa-chama-cha-kikomunisti-cha-vietnam/

https://www.jamhurimedia.co.tz/rais-samia-awataka-watanzania-kudumisha-mila-na-desturi-na-si-kuiga-tamaduni-zingine/

https://www.jamhurimedia.co.tz/rais-samia-afunga-tamasha-la-tatu-la-utamaduni-la-kitaifa-songea/

https://www.jamhurimedia.co.tz/rais-samia-akagua-ukarabati-na-upanuzi-wa-kiwanja-cha-ndege-songea/

https://www.jamhurimedia.co.tz/viongozi-wala-rushwa-hawakubaliki/

https://www.jamhurimedia.co.tz/majaliwa-mataifa-madogo-yaungwe-mkono-kiuchumi/

https://www.jamhurimedia.co.tz/polisi-tunawashikilia-mbowe-na-lisu-kwa-kujihusisha-na-maandamano/

https://www.jamhurimedia.co.tz/rais-akiangalia-vikundi-vya-ngoma-ya-asili-ruvuma/

https://www.jamhurimedia.co.tz/rais-samia-awasili-ruvuma-kwa-ziara-ya-kikazi/

https://www.jamhurimedia.co.tz/bashe-atoa-bei-elekezi-ya-mahindi-ruvuma/

https://www.jamhurimedia.co.tz/hii-taarifa-ipuuze/

https://www.jamhurimedia.co.tz/tpa-ujenzi-wa-bandari-mpya-ya-mbamba-bay-kuleta-ajira-kukuza-uchumi/

https://www.jamhurimedia.co.tz/rais-samia-aanza-ziara-ruvuma-leo/

https://www.jamhurimedia.co.tz/rais-samia-mgeni-rasmi-tamasha-la-utamaduni-songea-rais-samia-ndumbaro-atembelea-maonesho/

https://www.jamhurimedia.co.tz/miaka-10-ya-rsa-mwakihaba-atoa-onyo-kwa-madereva-wanaovunja-sheria/

https://www.jamhurimedia.co.tz/rais-samia-kuutembelea-mkoa-ruvuma-wananchi-watakiwa-kujitokeza-kumpokea/

https://www.jamhurimedia.co.tz/bashe-aleta-tabasamu-namtumbo-awarejeshea-hekta-3000-kwa-wakulima/

https://www.jamhurimedia.co.tz/watanzania-tuendelee-kudumisha-amani-dk-biteko/

https://www.jamhurimedia.co.tz/waziri-ndumbaro-agawa-vitabu-vya-kiada-songea-boys-vya-milioni-27-2/

https://www.jamhurimedia.co.tz/tassim-yaandaa-maonyesho-ya-viwanda-vidogo-dodoma/

https://www.jamhurimedia.co.tz/tanzania-ya-sita-duniani-kwa-ongezeko-la-watalii/

https://www.jamhurimedia.co.tz/benki-ya-akiba-yazindua-kampeni-tupo-mtaani-kwako/

https://www.jamhurimedia.co.tz/vijana-shikamaneni-kulinda-amani-ya-nchi-yetu-dk-biteko/

https://www.jamhurimedia.co.tz/waziri-ndumbaro-awataka-wazazi-kukemea-mmomonyoko-wa-maadili/

https://www.jamhurimedia.co.tz/tamasha-la-utamaduni-kitaifa-lafunguliwa-songea/

https://www.jamhurimedia.co.tz/rais-samia-ateta-igp-wambura-ikulu-jijini-dar-es-salaam/

https://www.jamhurimedia.co.tz/kafulila-aipongeza-cbe-kwa-ubunifu/

https://www.jamhurimedia.co.tz/rais-mwinyi-aipongeza-airpay-uzinduzi-mifumo-ya-kidijitali-ya-zeea/

https://www.jamhurimedia.co.tz/uchunguzi-wa-kisayansi-umesaidia-kuunganisha-wahalifu-na-tuhuma-zinazowakabili-kiurahisi/

https://www.jamhurimedia.co.tz/wanachama-wa-chadema-act-wazalendo-62-wahamia-ccm-kibaha-mji/

https://www.jamhurimedia.co.tz/dk-biteko-aagiza-kigoma-kuingizwa-kwenye-gridi-kabla-ya-2025/

https://www.jamhurimedia.co.tz/nishati-safi-inamuondolea-adha-mtoto-wa-kike-kijaji/

https://www.jamhurimedia.co.tz/maendeleo-ni-makubwa-nchini-watanzania-tumuunge-mkono-rais-samia-mathias-canal/

https://www.jamhurimedia.co.tz/mhagaa-serikali-yatenga-bil-1-upimaji-afya-nyumba-kwa-nyumba/

https://www.jamhurimedia.co.tz/zaidi-ya-watu-70000-waliojitolea-kuipigania-urusi-wafa-ukraine/

https://www.jamhurimedia.co.tz/un-yaridhia-israel-kuondoka-palestina/

https://www.jamhurimedia.co.tz/msongozi-awashauri-wanawake-kugombea-nafasi-za-wenyeviti-serikali-ya-mtaa/

https://www.jamhurimedia.co.tz/waziri-mhagama-afurahishwa-na-msd-inavyookoa-maisha-ya-watoto-njiti/

https://www.jamhurimedia.co.tz/rais-samia-awaapisha-viongozi-mbalimbali/

https://www.jamhurimedia.co.tz/tef-yapongeza-uteuzi-bodi-ya-ithibati-ya-wanahabari/

https://www.jamhurimedia.co.tz/waziri-mkuu-amwakilisha-rais-samia-mkutano-wa-baraza-kuu-la-umoja-wa-mataifa/

https://www.jamhurimedia.co.tz/vituo-vya-zana-za-kilimo-kujengwa-nchi-nzima-wanaowanyonya-wakulima-kukiona/

https://www.jamhurimedia.co.tz/serikali-kuendelea-kutekeleza-mkakati-wa-nishati-safi-ya-kupikia/

https://www.jamhurimedia.co.tz/tasac-yakabidhiwa-boti-na-ofisi-ya-waziri-mkuu-kuimarisha-ulinzi-wa-bahari/

https://www.jamhurimedia.co.tz/waziri-jafo-ataka-wananchi-kuacha-kuchanganya-mazao/

https://www.jamhurimedia.co.tz/asilimia-75-ya-watanzania-wanatumia-simu-za-mkononi-milioni-35-wanatumia-mtandao-wa-intanenti/

https://www.jamhurimedia.co.tz/uvimbe-uliomtesa-kwa-miaka-10-watolewa-na-mabingwa-wa-rais-samia/

https://www.jamhurimedia.co.tz/taec-kuwa-mlezi-wa-programu-maalum-ya-diploma-masomo-ya-teknolojia-ya-nyuklia/

https://www.jamhurimedia.co.tz/lukuvi-rais-samia-hana-deni-huduma-ya-maji-ubungo/

https://www.jamhurimedia.co.tz/mashindano-ya-kuogelea-afrika-kufanyika-zbar/

https://www.jamhurimedia.co.tz/waziri-bashe-awataka-wakulima-wafugaji-kuishi-kwa-amani/

https://www.jamhurimedia.co.tz/matumizi-ya-tehama-mahakamani-yamesaidia-kupunguza-mrundikano-wa-mashauri-prof-gabriel/

https://www.jamhurimedia.co.tz/makonda-abaini-upotevu-wa-bil-1-3-sekondari-ya-wasichana-longido/

https://www.jamhurimedia.co.tz/mchezo-wa-raga-waongeza-mahusiano-kati-ya-tanzania-na-ufaransa/

https://www.jamhurimedia.co.tz/serikali-yaweka-bilioni-81-ujenzi-bandari-ya-mbambabay/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-toleo-maalum/

https://www.jamhurimedia.co.tz/walimu-wadau-wa-wapata-mafunzo-matumizi-fasaha-ya-lugha-ya-kiswahili/

https://www.jamhurimedia.co.tz/kapinga-ashuhudia-fainali-doto-cup-2024/

https://www.jamhurimedia.co.tz/rais-samia-afanya-mazungumzo-na-princess-sophie-ikulu-jijini-dar-es-salaam/

https://www.jamhurimedia.co.tz/dk-biteko-mgeni-rasmi-hafla-ya-uwekaji-jiwe-la-msingi-mradi-wa-kuzalisha-umeme-mto-malagarasi/

https://www.jamhurimedia.co.tz/vikundi-vya-wajasiriamalia-vyanufaika-na-mitaji-wezeshi-ya-crdb-mil-101-6/

https://www.jamhurimedia.co.tz/rais-samia-amedhamiria-kuifungua-kigoma-dk-biteko/

https://www.jamhurimedia.co.tz/ewura-marufuku-kuunganisha-umeme-majumbani-kama-huna-leseni/

https://www.jamhurimedia.co.tz/mashindano-knk-cup-2024-yahitimishwa-mabingwa-wa-bukombe-karagwe-kuchuana/

https://www.jamhurimedia.co.tz/rais-mstaafu-kikwete-atoa-mafunzo-kwa-mawaziri-wa-afya-elimu-marekani/

https://www.jamhurimedia.co.tz/akutwa-ameuawa-porini/

https://www.jamhurimedia.co.tz/dk-nchimbi-ashiriki-kikao-cha-baraza-kuu-la-uvccm/

https://www.jamhurimedia.co.tz/tabora-tumepiga-vita-mafudi-umeme-vishoka-ras-tabora/

https://www.jamhurimedia.co.tz/wanawake-viongozi-walaani-kauli-za-uvunjifu-wa-amani/

https://www.jamhurimedia.co.tz/rais-samia-akizungumza-kabla-ya-kufunga-mkutano-maafisa-wakuu-waandamizi-wa-polisi/

https://www.jamhurimedia.co.tz/viongozi-wastaafu-wa-polisi-wakiwa-kwenye-mkutano-mkuu/

https://www.jamhurimedia.co.tz/gwaride-la-watoto-likipita-mbele-ya-rais-samia/

https://www.jamhurimedia.co.tz/matukio-mbalimbali-kwenye-maadhimisho-ya-miaka-60-ya-jeshi-la-polisi-kilimanjaro/

https://www.jamhurimedia.co.tz/gwaride-la-heshima-la-polisi-tanzania-likipita-mbele-ya-rais-samia/

https://www.jamhurimedia.co.tz/rais-samia-ashiriki-maadhimisho-miaka-60-ya-jeshi-la-polisi/

https://www.jamhurimedia.co.tz/rais-samia-anaamini-katika-ushirikiano-na-viongozi-wa-dini-dk-biteko/

https://www.jamhurimedia.co.tz/watumia-sherehe-za-ubatizo-kukeketa-watoto-serikali-yaonya/

https://www.jamhurimedia.co.tz/ndumbaro-azungumzia-umuhimu-wa-tamasha-utamaduni-mkoani-ruvuma/

https://www.jamhurimedia.co.tz/bashe-aridhishwa-na-kazi-nzuri-iliyofanywa-na-asa/

https://www.jamhurimedia.co.tz/dk-kijaji-tanzania-yazuia-tani-216-za-kemikali-hatari-kwa-tabaka-la-ozoni/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-septemba-17-23-2024/

https://www.jamhurimedia.co.tz/mashindano-ya-kuogelea-kitaifa-yafana-dar/

https://www.jamhurimedia.co.tz/mabweni-ya-kuchukua-wanafunzi-12000-kujengwa-kwa-ubia-dar/

https://www.jamhurimedia.co.tz/trump-anusurika-jaribio-jingine-la-mauaji/

https://www.jamhurimedia.co.tz/serikali-bilioni-830-kukabiliana-na-athari-za-el-nino/

https://www.jamhurimedia.co.tz/padri-kitima-ninyi-nyote-ni-ndugu-mkaishi-kwa-upendo/

https://www.jamhurimedia.co.tz/serikali-kujenga-upya-daraja-la-mbwemkuru-nakiu-lindi/

https://www.jamhurimedia.co.tz/jwtz-waibuka-mshindi-wa-jumla-mashindano-ya-bammata/

https://www.jamhurimedia.co.tz/waziri-bashe-rais-samia-hana-deni-kwa-watanzania-katika-sekta-ya-kilimo/

https://www.jamhurimedia.co.tz/tuvumiliane-na-kuheshimiana-kama-watanzania-dk-biteko/

https://www.jamhurimedia.co.tz/askofu-bagonza-mfumo-uliopo-unaruhusu-kupiga-kura-na-si-kuchagua/

https://www.jamhurimedia.co.tz/rais-wa-komoro-aliyeshambuiwa-na-polisi-kwa-kisu-anaendelea-vyema/

https://www.jamhurimedia.co.tz/watu-37-wahukumiwa-kifo-kwa-jaribio-la-mapinduzi-drc/

https://www.jamhurimedia.co.tz/tanzania-yangara-tamasha-la-mabalozi-uholanzi-2024/

https://www.jamhurimedia.co.tz/waziri-mavunde-awataka-watanzania-kuchangamkia-manunuzi-ya-bidhaa-ya-trilioni-3-1-migodini/

https://www.jamhurimedia.co.tz/dk-biteko-ahimiza-wanawake-kutumia-mifuko-ya-uwezeshaji-wananchi-kiuchumi/

https://www.jamhurimedia.co.tz/mkunda-awavisha-nishani-majenerali-wa-jwtz-kwa-niaba-ya-rais/

https://www.jamhurimedia.co.tz/viongozi-soko-la-machinga-dodoma-wasimamishwa-kupisha-uchunguzi/

https://www.jamhurimedia.co.tz/mzee-mwinyi-alijiuzulu-akamsaidia-nyerere-masauni-msaidie-rais-samia/

https://www.jamhurimedia.co.tz/airpay-tanzania-wadhamini-tamasha-la-pili-fahari-ya-zanzibar-rais-mwinyi-kulizindua/

https://www.jamhurimedia.co.tz/women-tapo-na-akhst-wasaini-makubaliano-kusaidia-huduma-za-afya-kwa-wanawake-wachuuzi/

https://www.jamhurimedia.co.tz/mbarawa-atembelea-ujenzi-wa-matenki-ya-kuhifadhia-mafuta-tpaapongeza/

https://www.jamhurimedia.co.tz/heslb-wabadilishana-hati-ya-makubaliano-na-tra/

https://www.jamhurimedia.co.tz/mpina-nipo-tayari-kuweka-tofauti-zangu-na-bashe-wakutana-live/

https://www.jamhurimedia.co.tz/ccm-walaani-kampeni-ya-samia-must-go/

https://www.jamhurimedia.co.tz/tume-huru-ya-uchaguzi-yatoa-ruksa-kwa-wafungwa-kupiga-kura/

https://www.jamhurimedia.co.tz/tbb-kufanya-ones-home-la-ste-oktoba-11-2024-dar-es-salaam/

https://www.jamhurimedia.co.tz/polisi-wapiga-stop-maandamano-ya-chadema/

https://www.jamhurimedia.co.tz/ttb-yazindua-onesho-la-nane-la-ste-2024/

https://www.jamhurimedia.co.tz/rita-zaidi-ya-asilimia-99-75-ya-vyeti-vimehakikiwa/

https://www.jamhurimedia.co.tz/sakata-la-yusuph-kagoma-lafika-pabaya/

https://www.jamhurimedia.co.tz/serikali-yavuna-trilioni-1-8-kupitia-sekta-ya-uziduaji-nchini/

https://www.jamhurimedia.co.tz/chadema-kuandamana-septemba-23/

https://www.jamhurimedia.co.tz/dc-nyasa-usimamizi-mbovu-umechangia-halmashauri-nyasa-kushindwa-kufikia-malengo/

https://www.jamhurimedia.co.tz/tma-yasisitiza-umuhimu-matumizi-ya-huduma-za-hali-ya-hewa-kwa-wadau-wa-ununuzi/

https://www.jamhurimedia.co.tz/wanaume-kutoka-jamii-ya-kimasai-watetea-maslahi-ya-wanawake/

https://www.jamhurimedia.co.tz/dcea-yasihi-watu-wa-forodha-kuongeza-umakini-kwenye-ukaguzi-bidhaa/

https://www.jamhurimedia.co.tz/shirikisho-la-umoja-wa-machinga-nchini-kufanya-mabadiliko-ya-katiba/

https://www.jamhurimedia.co.tz/wizara-ya-fedha-yakemea-nyonya-damu-watanzania-watakiwa-kulinda-fedha-zao/

https://www.jamhurimedia.co.tz/bashe-mpina-uwe-na-shukrani-kwa-serikali-chezea-sekta-nyingine-si-kilimo/

https://www.jamhurimedia.co.tz/jafo-aipa-tano-tpa-uboreshaji-miundombinu-ya-kutolea-huduma-katika-bandari-zake/

https://www.jamhurimedia.co.tz/tpa-wma-watakiwa-kusimamia-kikamilifu-flow-meter/

https://www.jamhurimedia.co.tz/waziri-aweso-amtumbua-mkurugenzi-mlevi-chato/

https://www.jamhurimedia.co.tz/lissu-ataka-vyombo-vya-usalama-vichunguzwe-na-visafishwe/

https://www.jamhurimedia.co.tz/iran-yawekewa-vikwazo-madai-ya-upelekaji-makombora-urusi/

https://www.jamhurimedia.co.tz/trump-harris-wapambana-kwenye-mdahalo/

https://www.jamhurimedia.co.tz/wafahamu-al-ahly-tripoli-wapinzani-wa-simba-shirikisho/

https://www.jamhurimedia.co.tz/azaki-sekta-binafsi-na-umma-kushirikiana-kuleta-maendeleo/

https://www.jamhurimedia.co.tz/mikoa-minne-kunufaika-na-nishati-safi-ya-kupika/

https://www.jamhurimedia.co.tz/rais-samia-mgeni-rasi-tamasha-la-utamaduni-songea/

https://www.jamhurimedia.co.tz/watahiniwa-1230780-wafanya-mtihani-wa-darasa-la-saba-leo/

https://www.jamhurimedia.co.tz/simbachawane-ateta-na-jakaya-kikwete/

https://www.jamhurimedia.co.tz/watoto-23-wafanyiwa-upasuaji-wa-moyo-jkci/

https://www.jamhurimedia.co.tz/ugonjwa-wa-miguu-na-midomo-unaoshambulia-mifugo-kutovuka-mipaka-ya-nchi-za-eac-na-sadc/

https://www.jamhurimedia.co.tz/dk-biteko-amfariji-angelah-kairuki/

https://www.jamhurimedia.co.tz/dk-biteko-rais-samia-ameelekeza-rasilimali-zinazochimbwa-nchini-ziwanufaishe-watanzania/

https://www.jamhurimedia.co.tz/utafiti-waonyesha-ushiriki-wa-vijana-kwenye-masuala-ya-demokrasia-ni-hafifu/

https://www.jamhurimedia.co.tz/dcea-yakamata-watu-watano-dar-wakiwa-na-kilogramu-1815-za-skanka/

https://www.jamhurimedia.co.tz/mshtakiwa-akwamisha-kesi-kwa-madai-kuwa-mgonjwa/

https://www.jamhurimedia.co.tz/polisi-kinondoni-waadhimisha-miaka-60-ya-polisi-tanzania/

https://www.jamhurimedia.co.tz/mbio-za-al-irshaad-zafana-dar/

https://www.jamhurimedia.co.tz/serikali-kutumia-ndege-kuzuia-uvuvi-haramu/

https://www.jamhurimedia.co.tz/tanzania-bado-inakabiliwa-na-uharibfu-wa-mazingira-dk-mpango/

https://www.jamhurimedia.co.tz/mazishi-ya-ali-mohamed-kibao-jijini-tanga/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-septemba-10-16-2024/

https://www.jamhurimedia.co.tz/mkumbo-serikali-kuendelea-kushirikiana-na-asasi-za-kiraia-bila-kikwazo/

https://www.jamhurimedia.co.tz/vijana-watakiwa-kutumia-vizuri-mitandao/

https://www.jamhurimedia.co.tz/fk-biteko-asisitiza-maadili-weledi-na-uwajibilajo-katika-ununuzi-wa-umma/

https://www.jamhurimedia.co.tz/rostam-azizi-atoa-tamko-kuhusu-mauaji-ya-kiongozi-wa-chadema/

https://www.jamhurimedia.co.tz/rostam-azizi-asikitishwa-na-kifo-cha-marehemu-mohamed-kibao/

https://www.jamhurimedia.co.tz/ccm-yatoa-pole-kifo-cha-kada-chadema/

https://www.jamhurimedia.co.tz/ushiriki-makundi-mbalimbali-katika-kutoa-maoni-una-mchango-mkubwa-kufanikisha-maendeleo/

https://www.jamhurimedia.co.tz/polisi-waongeza-nguvu-tukio-la-mauaji-ya-kibao/

https://www.jamhurimedia.co.tz/vijana-kujadili-tanzania-waitakayo-wiki-ya-azaki/

https://www.jamhurimedia.co.tz/rea-yaendelea-kutekeleza-dhamira-ya-rais-samia-kwa-vitendo/

https://www.jamhurimedia.co.tz/tma-yawakubusha-wahandisi-kuzingatia-huduma-za-hali-ya-hewa-katika-utekelezaji-wa-miradi/

https://www.jamhurimedia.co.tz/mbunge-ole-lekaita-ampa-tano-rais-samia/

https://www.jamhurimedia.co.tz/hapi-viongozi-waliopo-madarakani-wawajibike-kwa-wananchi/

https://www.jamhurimedia.co.tz/jesh-la-polisi-laanza-uchuguzi-wa-aliyeshushwa-kwenye-basi/

https://www.jamhurimedia.co.tz/tanzania-uingereza-kuimarisha-ushirikiano-sekta-ya-nishati/

https://www.jamhurimedia.co.tz/watu-12-wafariki-33-wajeruhiwa-kwa-ajali-mbeya/

https://www.jamhurimedia.co.tz/hapi-umoja-na-utendaji-nguzo-ya-ccm-kushika-dola-uchaguzi-2024-2025/

https://www.jamhurimedia.co.tz/awataka-wakandarasi-mradi-wa-umwagiliaji-skimu-ya-mkombozi-iringa-kuongeza-kasi/

https://www.jamhurimedia.co.tz/waziri-jafo-atembelea-cbe-na-kutoa-maagizo/

https://www.jamhurimedia.co.tz/naibu-katibu-mkuu-ccm-aanza-ziara-shinyanga/

https://www.jamhurimedia.co.tz/rais-dk-samia-azungumza-na-wawekezaji-mbalimbali-nchini-china/

https://www.jamhurimedia.co.tz/waziri-mkuu-atoa-maelekezo-uendeshaji-mradi-wa-sgr/

https://www.jamhurimedia.co.tz/mradi-mkubwa-wa-maji-ziwa-victoria-kuinusuru-biharamulo/

https://www.jamhurimedia.co.tz/rais-samia-ampandisha-cheo-afisa-wa-polisi/

https://www.jamhurimedia.co.tz/shindano-la-kriket-kufuzu-kombe-la-dunia-kufanyika-septemba-20/

https://www.jamhurimedia.co.tz/si-sahihi-kufanya-ukaguzi-katika-kaya-kubaini-wanaotumia-kuni-au-mkaa/

https://www.jamhurimedia.co.tz/shughuli-za-kibinadamu-kwenye-shoroba-chanzo-cha-migongano/

https://www.jamhurimedia.co.tz/rais-samia-ashiriki-mkutano-unaohusu-ukuaji-wa-viwanda-kilimo-cha-kisasa-jijini-beijing/

https://www.jamhurimedia.co.tz/papa-na-imamu-mkuu-wa-indonesia-watoa-wito-wa-pamoja-wa-amani/

https://www.jamhurimedia.co.tz/wafariki-kwa-mganga-wakitafuta-dawa-ya-biashara-wazikwa-kwa-siri/

https://www.jamhurimedia.co.tz/rowen-william-achaguliwa-kuwania-ballon-dor/

https://www.jamhurimedia.co.tz/mwanafunzi-wa-miaka-14-awaua-wenzake-kwa-bunduki-marekani/

https://www.jamhurimedia.co.tz/kiongozi-wa-upinzani-uganda-bobi-wine-kufanyiwa-upasuaji/

https://www.jamhurimedia.co.tz/spika-wa-bunge-ukraine-ajiuzulu/

https://www.jamhurimedia.co.tz/makalla-ccm-hatubebwi-tumejipanga/

https://www.jamhurimedia.co.tz/rc-chalamila-apokea-majina-ya-wafanyabiashara-wa-soko-la-kariakoo/

https://www.jamhurimedia.co.tz/serikali-kuendelea-kutenga-fedha-za-kukarabati-barabara-korofi-nchini/

https://www.jamhurimedia.co.tz/majaliwa-tanzania-kujiimarisha-zaidi-kidiplomasia/

https://www.jamhurimedia.co.tz/tanzania-kinara-wa-uwekezaji-mkubwa-wa-madini-kwa-kampuni-kutoka-australia/

https://www.jamhurimedia.co.tz/wenye-ulemavu-wapewa-nafasi-kugombea-na-kushiriki-uchaguzi-2024-2025/

https://www.jamhurimedia.co.tz/chauma-wakulima-wa-mbaazi-wamuangukia-rais-samia/

https://www.jamhurimedia.co.tz/isoc-tz-yawajengea-uwezo-vijana-katika-usimamizi-wa-mitandao/

https://www.jamhurimedia.co.tz/rais-samia-akutana-na-kufanya-mazungumzo-na-rais-wa-china-xi-jinping/

https://www.jamhurimedia.co.tz/ubelgiji-yaunga-mono-agenda-ya-nishati-safi-dk-biteko/

https://www.jamhurimedia.co.tz/law-school-itafsiri-mabadiliko-kama-kengele/

https://www.jamhurimedia.co.tz/wapiga-kura-wapya-491050-kuandikishwa-mara-simiyu-na-manyara/

https://www.jamhurimedia.co.tz/azam-fc-wamtimua-kocha-dabo-na-wasaidizi-wake/

https://www.jamhurimedia.co.tz/israel-mwenda-kwa-sasa-sina-timu-yoyote/

https://www.jamhurimedia.co.tz/uingereza-yasitisha-baadhi-ya-mauzo-ya-silaha-kwa-israel/

https://www.jamhurimedia.co.tz/drc-watu-129-wameuawa-katika-jaribio-la-kutoroka-gerezani/

https://www.jamhurimedia.co.tz/dhambi-ya-kuiua-ngorongoro/

https://www.jamhurimedia.co.tz/mafanikio-ya-kiuchumi-indonesia-yaihamasisha-tanzania-kujifunza/

https://www.jamhurimedia.co.tz/mchengerwa-dart-fanyeni-mchakato-haraka-kuondoa-adha-ya-usafiri/

https://www.jamhurimedia.co.tz/rais-samia-akiwasili-uwanja-wa-ndege-wa-kimataifa-wa-beijing-china/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-septemba-3-9-2024/

https://www.jamhurimedia.co.tz/rais-dk-samia-ateua-ahamisha-vituo-vya-kazi/

https://www.jamhurimedia.co.tz/madagascar-yaridhia-atakayebaka-watoto-ahasiwe/

https://www.jamhurimedia.co.tz/ligi-ya-kihenzile-cup-yazinduliwa/

https://www.jamhurimedia.co.tz/serikali-imelitambua-deni-la-kiwira-coal-mine-la-bilioni-1-52/

https://www.jamhurimedia.co.tz/tasa-yatahadharisha-uwepo-wa-upepo-mkali/

https://www.jamhurimedia.co.tz/tanzania-ipo-tayari-kwa-uwekezaji-utakaoongeza-thamani-ya-madini-ndani-ya-nchi/

https://www.jamhurimedia.co.tz/ofisi-ya-mganga-mkuu-dar-usaid-afya-yangu-mama-na-mtoto-yawanoa-kina-mama-50/

https://www.jamhurimedia.co.tz/rais-samia-kufanya-ziara-ya-kikazi-china/

https://www.jamhurimedia.co.tz/dc-longido-atenguliwa/

https://www.jamhurimedia.co.tz/amir-jeshi-mkuu-rais-dk-samia-akizindua-kitabu-cha-miaka-60-ya-jwtz/

https://www.jamhurimedia.co.tz/polisi-wanawake-tanzania-washiriki-mafunzo-marekani/

https://www.jamhurimedia.co.tz/rais-samia-kushiriki-mkutano-focac/

https://www.jamhurimedia.co.tz/nfra-wapewa-saa-72-kulipa-wauzaji-mazao/

https://www.jamhurimedia.co.tz/wanafunzi-watatu-dereva-wafa-katika-ajali/

https://www.jamhurimedia.co.tz/samia-ashiriki-mashindano-ya-quran/

https://www.jamhurimedia.co.tz/rais-samia-kuongoza-ujumbe-wa-tanzania-mkutano-wa-focac-nchini-china/

https://www.jamhurimedia.co.tz/waomba-uundaji-sera-ushirikishe-jamii/

https://www.jamhurimedia.co.tz/mko-wapi-viongozi-wa-dini-mbona-mpo-kimya-watu-wanapotea-lema/

https://www.jamhurimedia.co.tz/bei-ya-umeme-tanzania-ni-nafuu-kuliko-nchi-nyingine-za-afrika-mashariki-kapinga/

https://www.jamhurimedia.co.tz/madereva-kibaha-mjini-wampongeza-dk-shemwelekwa-kwa-tuzo-maalum/

https://www.jamhurimedia.co.tz/rais-samia-amwaga-mabilioni-kuboresha-sekta-ya-elimu-afya-halmashauri-ya-mji-kibaha/

https://www.jamhurimedia.co.tz/tista-watangaza-matokeo-ya-somo-la-elimu-ya-dini-ya-kiislamu/

https://www.jamhurimedia.co.tz/tanzania-yajipanga-kutumia-nishati-ya-nyuklia-kuzalisha-umeme-dk-biteko/

https://www.jamhurimedia.co.tz/elimu-matumizi-bora-ya-ardhi-kupunguza-migongano-baina-ya-binadamu-na-wanyama/

https://www.jamhurimedia.co.tz/mwanzilishi-wa-mtandao-wa-telegram-kufikishwa-mahakamani/

https://www.jamhurimedia.co.tz/aliyepatikana-na-mafuvu-ya-vichwa-vya-binadamu-uganda-kushtakiwa/

https://www.jamhurimedia.co.tz/treni-la-abiria-kigoma-tabora-lapata-ajali-uvinza/

https://www.jamhurimedia.co.tz/rais-dk-samia-azindua-ndege-za-mafunzo-ya-awali-kwa-marubani-jwtz/

https://www.jamhurimedia.co.tz/uwt-kibaha-mjini-yamuunga-mkono-rais-samia-mapinduzi-nishati-safi/

https://www.jamhurimedia.co.tz/dk-ndugulile-wa-tanzania-achaguliwa-mkurugenzi-wa-who-afrika/

https://www.jamhurimedia.co.tz/wafugaji-pwani-waitikia-wito-ufugaji-kisasa/

https://www.jamhurimedia.co.tz/kisiwa-cha-tembonyama-mafia-kupata-mwekezaji-na-kuchochea-mageuzi-sekta-ya-utalii/

https://www.jamhurimedia.co.tz/rais-samia-awasili-arusha-akitokea-kenya/

https://www.jamhurimedia.co.tz/masauni-jeshi-la-polisi-wajadili-amani/

https://www.jamhurimedia.co.tz/dk-ndunguile-ajinadi-mkutano-mkuu-wa-74-wa-who/

https://www.jamhurimedia.co.tz/dk-mpango-awaomba-nmb-kueneza-elimu-ya-bima-kwa-watumiaji-vyombo-vya-moto/

https://www.jamhurimedia.co.tz/majengo-ya-serikali-yazingatie-hudua-za-dharura/

https://www.jamhurimedia.co.tz/katambi-serikali-itaendelea-kuongeza-kasi-kutatua-migogoro-ya-kazi/

https://www.jamhurimedia.co.tz/wafungua-kesi-kupinga-tamisemi-kusimamia-uchaguzi-serikali-za-mtaa/

https://www.jamhurimedia.co.tz/nakubaliana-na-mbowe-iundwetume-kuchunguza-mauaji/

https://www.jamhurimedia.co.tz/raia-wa-china-aliyejifungua-mapacha-dar-ashukuru-kwa-huduma-nzuri/

https://www.jamhurimedia.co.tz/waziri-aweso-azindua-kampeni-ya-dawasa-mtaa-kwa-mtaa/

https://www.jamhurimedia.co.tz/marekani-yasisitiza-nia-ya-kuendeleza-mradi-wa-kabanga-nickel-na-kampuni-ya-bhp/

https://www.jamhurimedia.co.tz/tanzania-yawanoa-wataalamu-wa-hali-ya-hewa-afrika/

https://www.jamhurimedia.co.tz/rea-yamtaka-mwendelezaji-mradi-wa-kufua-umeme-maguta-iringa-kuongeza-kasi/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-agosti-27-septeba-2-2024/

https://www.jamhurimedia.co.tz/mjiandae-na-uchaguzi-mkuu-2025/

https://www.jamhurimedia.co.tz/wajipanga-kujadili-changamoto-za-mazingira/

https://www.jamhurimedia.co.tz/dk-nchimbi-akutana-na-waziri-liu-china/

https://www.jamhurimedia.co.tz/kocha-stars-ajibu-samatta-msuva-kutojumuishwa-kikosini/

https://www.jamhurimedia.co.tz/akiri-kuiba-mtoto-baada-ya-kuachika-mara-mbili/

https://www.jamhurimedia.co.tz/mtaalamu-bingwa-wa-nyonga-na-magoti-atua-dar/

https://www.jamhurimedia.co.tz/waziri-mavunde-aitaka-sekta-ya-binafsi-kujiandaa-na-mapinduzi-makubwa-ya-sekta-ya-madini/

https://www.jamhurimedia.co.tz/dcea-yateketeza-ekari-1165-za-mashamba-ya-bangi-morogoro/

https://www.jamhurimedia.co.tz/shule-ya-sekondari-hasnuu-makame-yaitikia-agizo-la-matumizi-ya-nishati-safi-ya-kupikia/

https://www.jamhurimedia.co.tz/watakaofiwa-na-wazazi-shule-ya-brilliant-kuendelea-na-masomo/

https://www.jamhurimedia.co.tz/hezbolllah-yasema-ilirusha-makombora-zaidi-ya-320/

https://www.jamhurimedia.co.tz/urusi-yaishambulia-ukraine-kwa-makombora-na-droni/

https://www.jamhurimedia.co.tz/tume-huru-ya-uchaguzi-yaviasa-vyama-vya-siasa/

https://www.jamhurimedia.co.tz/rais-samia-ashiriki-kilele-cha-tamasha-la-kizimkazi/

https://www.jamhurimedia.co.tz/waiomba-serikali-kuboresha-kiwango-cha-fidia-kwa-wanaoathirika-na-wanyamapori/

https://www.jamhurimedia.co.tz/rais-dkt-samia-suluhu-hassan-azindua-utalii-wa-kasa-katika-pango-la-salaam-kizimkazi/

https://www.jamhurimedia.co.tz/dc-kinondoni-aongoza-kampeni-ya-utunzwaji-mazingira/

https://www.jamhurimedia.co.tz/serikali-itaendelea-kutumia-tehama-kukuza-maendeleo-dk-biteko/

https://www.jamhurimedia.co.tz/majaliwa-ashuhudia-wanachama-wa-cuf-act-wazalendo-wakirejea-ccm/

https://www.jamhurimedia.co.tz/mweka-hazina-mbaroni-kwa-ubadhirifu-wa-fedha-za-kikundi/

https://www.jamhurimedia.co.tz/500-kutoka-asasi-za-kiraia-kushiriki-maadhimisho-wiki-ya-azaki-2024-arusha/

https://www.jamhurimedia.co.tz/rea-tutaendelea-kufanya-tafiti-za-bidhaa-za-nishati-safi-za-kupikia-zinazosambazwa-kwa-wananchi/

https://www.jamhurimedia.co.tz/rais-samia-aahidi-kusimamia-jwtz-kuwa-madhubuti-na-la-mfano-afrika/

https://www.jamhurimedia.co.tz/rais-dkt-samia-suluhu-akiwa-kwenye-picha-ya-pamoja-na-askari-wa-vikundi-mbalimbali-vya-jwtz-pwani/

https://www.jamhurimedia.co.tz/askari-endelezeni-mazoezi-ya-karati-cp-hamad/

https://www.jamhurimedia.co.tz/rais-samia-ameibeba-ajenda-ya-nishati-safi-ya-kupikia-kimataifa-dk-biteko/

https://www.jamhurimedia.co.tz/jkci-yaendelea-kuwa-kivutio-kwa-mataifa-ya-afrika/

https://www.jamhurimedia.co.tz/jjad-kagera-farmers-yamshukuru-rais-samia-kwa-bei-nzuri-ya-kahawa/

https://www.jamhurimedia.co.tz/madaktari-nane-wa-drc-waja-kujifunza-jkci/

https://www.jamhurimedia.co.tz/rais-samia-aweka-jiwe-la-msingi-ujenzi-wa-suluhu-sports-academy-eneo-la-kizimkazi/

https://www.jamhurimedia.co.tz/breaking-news-basi-lagongana-uso-kwa-uso-la-lori-la-mafuta-wanne-wafariki/

https://www.jamhurimedia.co.tz/dk-mpango-ahitimisha-ziara-yake-kwa-kuweka-jiwe-la-msingi-ujenzi-wa-skimu-ya-bbt/

https://www.jamhurimedia.co.tz/dk-mpango-uwekezaji-unaofanywa-na-serikali-sekta-ya-umwagiliaji-utamaliza-tatizo-la-njaa-nchini/

https://www.jamhurimedia.co.tz/mavuno-lapongeza-kuimarisha-ndoa-kagera/

https://www.jamhurimedia.co.tz/baraza-la-madiwani-kibaha-mji-yamuomba-rais-samia-kuendeleza-ardhi-ya-shirika-la-elimu/

https://www.jamhurimedia.co.tz/tma-waandishi-wajadili-namna-ya-kufikisha-taarifa-za-utabiri-mvua-msimu-wa-vuli/

https://www.jamhurimedia.co.tz/tawido-yawaomba-wadau-mbalimbali-kuunganisha-nguvu-ili-kudhibiti-vitendo/

https://www.jamhurimedia.co.tz/uwepo-wa-tawa-waongeza-hadhi-ya-tamasha-la-kizimkazi/

https://www.jamhurimedia.co.tz/dola-milioni-18-5-kudhibiti-mpox/

https://www.jamhurimedia.co.tz/zanzibar-kuweka-mkazo-zao-la-mwani/

https://www.jamhurimedia.co.tz/mtumishi-suma-jkt-tunduma-mbaroni-kwa-kuomba-na-kupokea-rushwa/

https://www.jamhurimedia.co.tz/katibu-chama-cha-ushirika-matandu-amcos-lindi-mbaroni-kwa-kuhujumu-uchumi/

https://www.jamhurimedia.co.tz/mloganzila-yawaita-wenye-shida-ya-nyonga-na-magoti/

https://www.jamhurimedia.co.tz/mkutano-wa-kimataifa-wa-uwekezaji-sekta-ya-madini-tanzania-kuwavuta-wawekezaji-duniani-mavunde/

https://www.jamhurimedia.co.tz/wizara-ya-nishati-yashiriki-tamasha-la-kizimkazi-zanzibar/

https://www.jamhurimedia.co.tz/dk-mpango-aweka-jiwe-la-msingi-ujenzi-wa-daraja-la-mto-hurui/

https://www.jamhurimedia.co.tz/wakili-mbedule-apia-jeki-halmashauri-ya-iringa/

https://www.jamhurimedia.co.tz/mbowe-wafundishe-chadema-siasa-za-tanzania/

https://www.jamhurimedia.co.tz/who-mpox-sio-aina-mpya-ya-uviko/

https://www.jamhurimedia.co.tz/rais-mstaafu-kikwete-akutana-na-makamu-wa-rais-nigeria-jiini-abuja/

https://www.jamhurimedia.co.tz/tls-yaitaka-polisi-kumfikisha-mahakamani-afande-aliyeagiza-binti-yombo-abakwe/

https://www.jamhurimedia.co.tz/waziri-mhagama-akabidhi-ofisi-kwa-waziri-lukuvi/

https://www.jamhurimedia.co.tz/ridhiwani-kikwete-anogesha-bonanza-la-nmb-day-kizimkazi-festival-2024/

https://www.jamhurimedia.co.tz/rais-samia-azindua-shule-ya-mil-800-iliyojengwa-makunduchi-na-nmb/

https://www.jamhurimedia.co.tz/wakandarasi-rea-fanyeni-kazi-kwa-uadilifu-na-kukamilisha-miradi-kwa-wakati-dk-biteko/

https://www.jamhurimedia.co.tz/vijiji-vitano-vyalipwa-bilioni-2-za-mrabaha-kutokana-na-uzalishaji-dhahabu-nyamongo-tarime/

https://www.jamhurimedia.co.tz/dk-nchemba-aihakikishia-jumuya-ya-kimataifa-kuboresha-mifumo-ya-kodi/

https://www.jamhurimedia.co.tz/rais-mwinyi-akutana-na-balozi-wa-india-nchini-tanzania-ikulu-zanzibar/

https://www.jamhurimedia.co.tz/milango-ipo-wazi-kwa-watoto-kufikia-ndoto-zao/

https://www.jamhurimedia.co.tz/halmashauri-pwani-zatakiwa-kusimamia-malengo-ya-utekelezaji-wa-mkataba-wa-lishe/

https://www.jamhurimedia.co.tz/dk-mwinyi-amsifu-samia-kuimarisha-umoja/

https://www.jamhurimedia.co.tz/ufunguzi-wa-kogamano-la-tatu-la-chama-cha-madereva-wa-serikali/

https://www.jamhurimedia.co.tz/rais-dkt-samia-na-watoto-zanzibar/

https://www.jamhurimedia.co.tz/serikali-kuongeza-thamani-ya-tanzanite/

https://www.jamhurimedia.co.tz/rais-samia-akifungua-skuli-ya-maandalizi-dkt-samia-suluhu-hassan-wakati-wa-shamrashamra-za-tamasha-la-kizimkazi-zanzibar/

https://www.jamhurimedia.co.tz/tma-yawahimizwa-wadau-kutoa-maoni-na-kujipanga-na-utabiri-wa-msimu-wa-vuli/

https://www.jamhurimedia.co.tz/serikali-ya-ruto-kurejesha-vipengee-vya-mswada-wa-fedha/

https://www.jamhurimedia.co.tz/maboresho-mahakama-ya-tanzania-yaivutia-mahakama-ya-malawi/

https://www.jamhurimedia.co.tz/zelensky-wanajeshi-wetu-wanatimiza-malengo-yao-huko-kursk/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-agosti-20-26-2024/

https://www.jamhurimedia.co.tz/dreamliner-ashindwa-kufika-zanzibar/

https://www.jamhurimedia.co.tz/smz-kuja-na-boti-za-mwendokasi/

https://www.jamhurimedia.co.tz/wagonjwa-30-kufanyiwa-upasuaji-nyonga-magoti/

https://www.jamhurimedia.co.tz/makamu-wa-rais-dkt-mpango-awapongeza-dawasa/

https://www.jamhurimedia.co.tz/baba-mama-lishe-5000-kupata-elimu-umuhimu-nishati-safi-ifikapo-2023-2026-interfini/

https://www.jamhurimedia.co.tz/serikali-yamwaga-bilioni-4-6-kuwezesha-umeme-maeneo-ya-migodi-ruvuma/

https://www.jamhurimedia.co.tz/dk-mpango-awasili-dodoma-kuanza-ziara-ya-kikazi-siku-nne/

https://www.jamhurimedia.co.tz/tanzania-mwenyeji-mkutano-wa-mafuta-gesi-machi-2025/

https://www.jamhurimedia.co.tz/rais-mwinyi-mwinyi-tamasha-la-kizimkazi-ni-fursa-ya-utalii-na-uwekezaji/

https://www.jamhurimedia.co.tz/msajili-vyama-vya-siasa-aongoza-kikao-cha-mashauriano-cha-vyama-vya-siasa-wanachama-tcd/

https://www.jamhurimedia.co.tz/jarida-la-mkulima-mbunifu-lafikia-wakulima-100000/

https://www.jamhurimedia.co.tz/bilioni-4-6-kupeleka-umeme-maeneo-ya-migodi-ruvuna-kapinga/

https://www.jamhurimedia.co.tz/kamanda-wa-hezbollah-auawa-katika-shambulizi-la-anga/

https://www.jamhurimedia.co.tz/tic-yatoa-semina-kwa-wafanyabiashara-ruvuma/

https://www.jamhurimedia.co.tz/kuna-faida-nyingi-tanzania-kuwa-mwenyekiti-wa-troika-sadc/

https://www.jamhurimedia.co.tz/rais-samia-akabidhiwa-rasmi-uenyekiti-wa-asasi-ya-siasa-ulinzi-na-usalama-sadc/

https://www.jamhurimedia.co.tz/300-wafariki-katika-mlipuko-wa-kipindupindu-sudan/

https://www.jamhurimedia.co.tz/madaktari-nchini-india-wafanya-mgomo-wa-kitaifa/

https://www.jamhurimedia.co.tz/who-kufunga-mipaka-hakutazuia-virusi-vya-mpox-kusambaa/

https://www.jamhurimedia.co.tz/rais-hichilema-ampa-tano-rais-samia-kwa-usimamizi-bora-wa-demokrasia/

https://www.jamhurimedia.co.tz/rais-dkt-samia-akiwa-pamoja-na-viongozi-wengine-katika-mkutano-wa-44-wa-sadc/

https://www.jamhurimedia.co.tz/rais-samia-na-maraisi-wengine-wakiwasili-kushiriki-mkutano-wa-44-sadc-harare-zimbabwe/

https://www.jamhurimedia.co.tz/amuua-mwanamke-kwa-kumnyonga-na-kamba/

https://www.jamhurimedia.co.tz/wakandarasi-mradi-wa-taza-kv-400-watakiwa-kukamilisha-kazi-kwa-wakati/

https://www.jamhurimedia.co.tz/rais-samia-ashiriki-mkutano-wa-wakuu-wa-nchi-na-serikali-wa-asasi-ya-siasa-ulinzi-na-usalama-ya-sadc-zimbabwe/

https://www.jamhurimedia.co.tz/trc-kuimarisha-mifumo-dhidi-ya-udanganyifu-wa-tiketi/

https://www.jamhurimedia.co.tz/rais-samia-amefanya-umeme-kuwa-si-anasa-kapinga/

https://www.jamhurimedia.co.tz/waziri-kombo-asisitiza-amani-na-usalama-katika-kanda-ya-sadc/

https://www.jamhurimedia.co.tz/bilioni-146-kutumika-matengenezo-ya-dharura-ujenzi-wa-madaraja-lindi/

https://www.jamhurimedia.co.tz/changamoto-uchakataji-mkonge-kupatiwa-ufumbuzi/

https://www.jamhurimedia.co.tz/ubalozi-waadhimisha-miaka-78-ya-uhuru-wa-india/

https://www.jamhurimedia.co.tz/tanzania-ipo-tayarri-kutumia-fursa-ya-soko-la-pamoja-kuuziana-umeme-dk-biteko/

https://www.jamhurimedia.co.tz/rc-makonda-aagiza-jengo-jipya-la-abiria-uwanja-wa-ndege-arusha-kuanza-kutumika-septemba-mosi-2024/

https://www.jamhurimedia.co.tz/siku-ya-vijana-duniani-yaambatana-na-maadhimisho-ya-taasisi-ya-amo-faundation/

https://www.jamhurimedia.co.tz/wizara-tatu-zajadili-hali-ya-uzalishaji-chumvi-nchini/

https://www.jamhurimedia.co.tz/tanzania-china-wasaini-makubaliano-ya-biashara-ya-asali/

https://www.jamhurimedia.co.tz/tasaf-wanufaika-18-403-zahitimu-na-kujiondoa-tasaf-pwani-roselyn/

https://www.jamhurimedia.co.tz/takukuru-yaokoa-mabilioni-ya-fedha-za-miradi-tabora/

https://www.jamhurimedia.co.tz/fundi-magari-ahukumiwa-kifungo-cha-maisha-kwa-kumlawiti-mtoto-wake/

https://www.jamhurimedia.co.tz/serikali-kuendelea-kutatua-changamoto-zinazozikabili-taasisi-za-dini-nchini/

https://www.jamhurimedia.co.tz/nembo-ya-uchaguzi-serikali-za-mitaa-yazinduliwa/

https://www.jamhurimedia.co.tz/rais-samia-apokelewa-na-gwaride-maalum-zimbabwe/

https://www.jamhurimedia.co.tz/rais-samia-awaapisha-viongozi-mbalimbali-ikulu-dar-es-salaam/

https://www.jamhurimedia.co.tz/tcb-kushirikiana-na-bunge-kuwainua-wajasiriamali-nchini/

https://www.jamhurimedia.co.tz/rais-samia-awasili-zimbabwe-kushiriki-mkutano-wa-44-wa-wakuu-wa-nchi-sadc/

https://www.jamhurimedia.co.tz/rais-dkt-samia-kuchukua-uenyekiti-asasi-ya-siasa-ulinzi-na-usalama-ya-sadc/

https://www.jamhurimedia.co.tz/tmx-tumeanza-msimu-wa-korosho-2024-2025/

https://www.jamhurimedia.co.tz/kunenge-wananchi-watoe-maoni-dira-ya-taifa-ya-maendeleo-2025-2050/

https://www.jamhurimedia.co.tz/rais-samia-apangua-mawaziri-amteua-lukuvi-kabudi/

https://www.jamhurimedia.co.tz/mkutano-wa-mico-halal-waibua-mambo-kuhusu-umuhimu-wa-bidhaa-za-halal/

https://www.jamhurimedia.co.tz/dawasa-watakiwa-kuongeza-nguvu-kukomesha-wizi-wa-mita/

https://www.jamhurimedia.co.tz/dcea-yaadhimisha-siku-ya-vijana-kwa-kutoa-elimu-arusha/

https://www.jamhurimedia.co.tz/serikali-kufanya-tathamini-maeneo-mbalimbali-nchini-kubaini-athari-za-mafuriko/

https://www.jamhurimedia.co.tz/rc-mara-atoa-wiki-sita-kwa-mkurugenzi-serengeti/

https://www.jamhurimedia.co.tz/madiwani-tabora-walaani-mwalimu-kulawiri-mwanafunzi/

https://www.jamhurimedia.co.tz/polisi-waachia-baadhi-ya-wanachama-na-viongozi-wa-chadema/

https://www.jamhurimedia.co.tz/idadi-ya-watalii-yaongezeka-pugu-kazimzumbwi-wafikia-21248-mtewa/

https://www.jamhurimedia.co.tz/tccia-yataka-wadau-washiriki-mkutano-wa-halal-kesho/

https://www.jamhurimedia.co.tz/mchungaji-mackenzie-ashtakiwa-kwa-kuwaamrisha-wafuasi-wake-wafunge-hadi-kufa-kenya/

https://www.jamhurimedia.co.tz/fcc-yaiomba-serikali-itupie-macho-makundi-maalum-na-kujiimarisha-kiuchumi/

https://www.jamhurimedia.co.tz/ndumbaro-asitisha-ujenzi-wa-shule-eneo-la-michezo-dar/

https://www.jamhurimedia.co.tz/waziri-kombo-kushiriki-mkutano-wa-mawaziri-wa-sadc-harare/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-agosti-13-19-2024/

https://www.jamhurimedia.co.tz/tef-waandishi-waliokamatwa-mbeya-waachiwe-haraka-bila-masharti/

https://www.jamhurimedia.co.tz/hospitali-ya-temeke-yazindua-kituo-cha-kusafishia-damu/

https://www.jamhurimedia.co.tz/ujenzi-wa-daraja-la-j-p-magufuli-upo-asilimia-90-ya-utekelezaji/

https://www.jamhurimedia.co.tz/nmb-kumkabidhi-rais-samia-shule-kuwanoa-wajasiriamali-700-kizimkazi-festival-2024/

https://www.jamhurimedia.co.tz/tax-afungua-mazoezi-ya-medani-umoja-2024-ya-jwtz-na-jeshi-la-china/

https://www.jamhurimedia.co.tz/rubani-afariki-dunia-baada-ya-helikopta-kuanguka-juu-ya-hoteli-australia/

https://www.jamhurimedia.co.tz/polisi-mbeya-wapiga-stop-maandamano/

https://www.jamhurimedia.co.tz/kusiluka-vijana-ingieni-kwenye-mfumo-wa-uchumi-kidijitali/

https://www.jamhurimedia.co.tz/rais-awasili-nchini-akitokea-rwanda-kwenye-uapisho-wa-rais/

https://www.jamhurimedia.co.tz/vyuo-vya-afya-valia-gharama-za-mafunzo-kwa-vitendo/

https://www.jamhurimedia.co.tz/serikali-kuchangia-bilioni-5-kuimarisha-shughuli-za-ushirika/

https://www.jamhurimedia.co.tz/ofisi-ya-msajili-psssf-wcf-waingia-ubia-kumiliki-kiwanda-cha-chai-mponde/

https://www.jamhurimedia.co.tz/tanesco-tumieni-umeme-uliopo-kufanya-matengenezo-dk-biteko/

https://www.jamhurimedia.co.tz/mbunge-kibaha-dc-kibaha-waungana-kuanzisha-kliniki-ya-wasanii/

https://www.jamhurimedia.co.tz/miili-yote-62-yapatikana-katika-ajali-ya-ndege-ya-brazil/

https://www.jamhurimedia.co.tz/tuzo-ya-chem-chem-yawasili-nchini-serikali-yapongeza/

https://www.jamhurimedia.co.tz/balozi-kombo-chumi-wateta-na-makamu-wa-kwanza-w-rais-zanzibar/

https://www.jamhurimedia.co.tz/watakiwa-kueneza-elimu-ya-mkataba-wa-cites-kulinda-viumbe-hai/

https://www.jamhurimedia.co.tz/idara-ya-uhamiaji-arusha-yakamata-raia-saba-wa-ethiopia-kwa-kuingia-nchini-kinyemela/

https://www.jamhurimedia.co.tz/kamati-ya-bunge-ya-bajeti-yaahidi-kuupa-msukumo-mradi-wa-eacop/

https://www.jamhurimedia.co.tz/jkt-kinara-wa-jumla-maonesho-ya-nanenane/

https://www.jamhurimedia.co.tz/serikali-kuongeza-fursa-za-kidigitali-kwa-vijana-kuleta-maendeleo-kiuchumi/

https://www.jamhurimedia.co.tz/nfra-yaanza-kutumoa-mizani-ya-kidigitali-kupimia-mazao/

https://www.jamhurimedia.co.tz/tcra-ongezeeni-umakini-katika-matumizi-ya-simu-usifungue-link-usiyoijua/

https://www.jamhurimedia.co.tz/breaking-news-mzee-magoma-ashindwa-kesi-atakiwa-kulipa-faini/

https://www.jamhurimedia.co.tz/sagcot-yaishukuru-usaid-kwa-kuendelea-kutoa-ufadhili-katika-miradi-mbalimbali/

https://www.jamhurimedia.co.tz/shirika-la-islands-of-peace-tanzania-lawafikia-zaidi-ya-wakulima-3500/

https://www.jamhurimedia.co.tz/tfnc-yaitaka-jamii-kuacha-dhana-potofu-kuhusu-virutubishi/

https://www.jamhurimedia.co.tz/tma-wananchi-fatilieni-taarifa-za-hali-ya-hewa/

https://www.jamhurimedia.co.tz/70076-2/

https://www.jamhurimedia.co.tz/mkurugenzi-mkuu-rea-ahamasisha-wananchi-kutumia-nishati-safi-ya-kupikia/

https://www.jamhurimedia.co.tz/madaktari-bingwa-wa-nyonga-kutoa-india-kufanya-upasuaji-wa-magoti-na-nyonga-dar/

https://www.jamhurimedia.co.tz/global-education-link-kupeleka-kundi-la-kwanza-nje-ya-nchi-wiki-ijayo/

https://www.jamhurimedia.co.tz/rc-ruvuma-awakumbusha-viongozi-kuzingatia-sheria-kanuni-ili-kurahisisha-utendajikazi/

https://www.jamhurimedia.co.tz/tfra-yawataka-wakulima-kujisajili-mapema-katika-mfumo-wao/

https://www.jamhurimedia.co.tz/wengi-waliotembela-banda-la-gcla-nanenane-wametaka-kujua-kuhusu-dna-kemikali/

https://www.jamhurimedia.co.tz/tphpa-yawashauri-wakulima-kuendelea-kutumia-mbegu-za-asili/

https://www.jamhurimedia.co.tz/daspa-wakulima-tumieni-mbegu-ya-mtama-aina-ya-tarusor1/

https://www.jamhurimedia.co.tz/watanzania-ikimbilieni-veta-kupata-ujuzi/

https://www.jamhurimedia.co.tz/rais-wa-tunisia-amfuta-kazi-waziri-mkuu/

https://www.jamhurimedia.co.tz/mwanariadha-akabidhiwa-benswra-ya-taifa-crdb-marathon/

https://www.jamhurimedia.co.tz/miradi-mitano-yenye-thamani-ya-bilioni-7-yabainika-kuwa-na-kasoro-ruvuma-takukuru/

https://www.jamhurimedia.co.tz/moi-yatoa-ushauri-kwa-magonjwa-ya-mifupa-masuala-ya-lishe-katika-maonesho-nanenane/

https://www.jamhurimedia.co.tz/wananchi-387-wapatiwa-msaada-wa-kisheria-katika-maonesho-nanenane/

https://www.jamhurimedia.co.tz/zaidi-ya-kampuni-50-zasajiliwa-na-brela-maonesho-nanenane/

https://www.jamhurimedia.co.tz/wizara-ya-afya-yawaita-wananchi-kutembelea-banda-lao-nanenane/

https://www.jamhurimedia.co.tz/bodi-ya-bima-ya-amana-yajidhatiti-kuimarisha-uwazi-katika-utendaji-wa-kampuni-za-bima/

https://www.jamhurimedia.co.tz/thbub-yalaani-kitendo-cha-binti-kufanyiwa-ukatili-na-vijana-watano/

https://www.jamhurimedia.co.tz/ewura-ccc-yatumia-maonesho-ya-wakulima-kuelimisha-matumizi-sahihi-ya-gesi/

https://www.jamhurimedia.co.tz/mbaroni-kwa-tuhuma-za-kusambaza-uongo-kifo-cha-binti-aliyedhalilishwa/

https://www.jamhurimedia.co.tz/simba-yanga-kuumana-kesho-kwa-mkapa/

https://www.jamhurimedia.co.tz/mtoto-aliyechinjwa-na-housegirl-aruhusiwa-kutoka-hospitali/

https://www.jamhurimedia.co.tz/uturuki-kujiunga-kesi-ya-mauaji-ya-kimbari-dhidi-ya-israel/

https://www.jamhurimedia.co.tz/marekani-yakamilisha-kujiondoa-kijeshi-niger/

https://www.jamhurimedia.co.tz/bilioni-tano-kujenga-hospitali-ya-rufaa-moro/

https://www.jamhurimedia.co.tz/kamanda-takukuru-ruvuma-aipa-tano-tarura/

https://www.jamhurimedia.co.tz/rais-samia-ataka-wizara-ya-nishati-kuongeza-kasi-usimamizi-miradi/

https://www.jamhurimedia.co.tz/ngamia-300-wakamatwa-mpakani-mwa-tanzania-na-kenya/

https://www.jamhurimedia.co.tz/rais-samia-ateua-wenyeviti-wa-bodi/

https://www.jamhurimedia.co.tz/tumejipanga-kutekeleza-mkakati-wa-taifa-nishati-safi-ya-kupikia-mramba/

https://www.jamhurimedia.co.tz/tmda-yawashauri-wananchi-kutembelea-banda-lao-kujifunza-matumizi-ya-dawa-nanenane/

https://www.jamhurimedia.co.tz/jeshi-laanza-rasmi-jukumu-la-kuiongoza-kwa-muda-bangladesh/

https://www.jamhurimedia.co.tz/rais-samia-aacha-alama-ya-kipekee-morogoro/

https://www.jamhurimedia.co.tz/wananchi-wajionea-utekelezaji-miadi-ya-gesi-asilia-nanenane/

https://www.jamhurimedia.co.tz/mwanafunzi-nit-abuni-mashine-ya-kusaidia-kulea-vifaranga/

https://www.jamhurimedia.co.tz/fcs-tcra-ccc-wakubaliana-kuimarisha-haki-za-watumiaji-mawasiliano/

https://www.jamhurimedia.co.tz/tarura-yaeleza-umuhimu-wa-maabara-katika-ujenzi-wa-barabara-zenye-viwango/

https://www.jamhurimedia.co.tz/takukuru-kinondoni-yapokea-malalamiko-8-yaendelea-na-mapambano/

https://www.jamhurimedia.co.tz/mradi-kijani-hai-wawa-neema-kwa-wakulima-wa-pamba/

https://www.jamhurimedia.co.tz/au-yaomba-vyombo-vya-habari-kuiandika-vizuri-afrika-kulinda-uhuru-wa-habari/

https://www.jamhurimedia.co.tz/tcaa-njooni-mjifunze-matumizi-ya-ndege-nyuki/

https://www.jamhurimedia.co.tz/erio-tembeleeni-fcc-kupata-elimu-kuhusu-bidhaa-bandia/

https://www.jamhurimedia.co.tz/mgina-taec-tuna-mchango-mkubwa-sekta-ya-kilimo/

https://www.jamhurimedia.co.tz/diwani-ahukumiwa-miaka-miwili-jela/

https://www.jamhurimedia.co.tz/uboreshaji-daftari-la-kudumu-la-wapiga-waanza-kagera-na-geita/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-agosti-6-12-2024/

https://www.jamhurimedia.co.tz/tnmc-jamii-ifahamu-haki-na-wajibu-wa-mgonjwa/

https://www.jamhurimedia.co.tz/bodi-ya-mkonge-kuwaunganisha-wakulima-na-masoko/

https://www.jamhurimedia.co.tz/rais-samia-awaalika-wawekezaji-kilombero-malinyi-na-ulanga/

https://www.jamhurimedia.co.tz/dcea-kilimo-cha-bhangi-na-mirungi-kinaondoa-uoto-wa-asili/

https://www.jamhurimedia.co.tz/cpa-kasore-itumieni-veta-kupata-ujuzi-na-kujiajiri/

https://www.jamhurimedia.co.tz/brela-yawaita-wakulima-kusajili-nembo-alama-za-biashara/

https://www.jamhurimedia.co.tz/tarura-yajipanga-kuhakikisha-wakulima-wanayafikia-masoko-kwa-kirahisi/

https://www.jamhurimedia.co.tz/wanyamapori-wanamchango-mkubwa-katika-sekta-ya-utalii/

https://www.jamhurimedia.co.tz/watu-karibu-100-wafa-maandamano-ya-bangladesh/

https://www.jamhurimedia.co.tz/wananchi-waendelea-kupata-msaada-wa-kisheria-kupitia-kampeni-ya-mama-samia-legal-kampeni/

https://www.jamhurimedia.co.tz/rais-samia-aridhia-vituo-75-vya-kupoza-umeme-kujengwa-nchini-kapinga/

https://www.jamhurimedia.co.tz/dk-mpango-ashiriki-kilele-cha-wiki-ya-mwananchi/

https://www.jamhurimedia.co.tz/yanga-yailamba-red-arrows-2-1-mchezo-wa-kirafiki/

https://www.jamhurimedia.co.tz/rais-samia-azungumza-na-wakazi-wa-mikumi/

https://www.jamhurimedia.co.tz/dk-mpango-asafiri-kwa-treni-kushiriki-yanga-day/

https://www.jamhurimedia.co.tz/rais-samia-akutana-na-mwalimu-wake-aliyemfundisha-chuo-kikuu-mzumbe/

https://www.jamhurimedia.co.tz/polisi-walaani-tukio-la-udhalilishaji/

https://www.jamhurimedia.co.tz/rais-samia-afungua-barabara-ya-kidatu-ifaraka-na-daraja-mto-ruaha-mkuu/

https://www.jamhurimedia.co.tz/tra-yajuoanga-kutoa-elimu-nanenane/

https://www.jamhurimedia.co.tz/wma-yaeleza-mchango-wake-katika-sekta-ya-kilimo/

https://www.jamhurimedia.co.tz/rwanda-yafunga-makanisa-4000/

https://www.jamhurimedia.co.tz/veta-yawaita-wananchi-kutembelea-banda-lao-nanenane/

https://www.jamhurimedia.co.tz/udom-yawashauri-wakulima-wafugaji-kutumia-mbinu-na-teknolojia-kukuza-sekta-ya-kilimo/

https://www.jamhurimedia.co.tz/nic-wakulima-jiungeni-na-bima-ya-kilimo/

https://www.jamhurimedia.co.tz/wasimulia-wanavyonufaika-na-kampeni-ya-mama-samia-legal-aid-morogoro/

https://www.jamhurimedia.co.tz/ccm-yaita-wenye-nia-kugombea-ubunge-eala/

https://www.jamhurimedia.co.tz/simba-day-yangara/

https://www.jamhurimedia.co.tz/wizara-ya-nishati-mtibwa-wajadili-ujenzi-njia-ya-umeme/

https://www.jamhurimedia.co.tz/shindano-la-kcb-east-africa-golf-tour-laanza-rasmi-lugalo-gofu/

https://www.jamhurimedia.co.tz/historia-yaandikea-utekelezsji-mradi-wa-chuma-maganga/

https://www.jamhurimedia.co.tz/wanasheria-watatua-migogoro-ziara-ya-rais-samia-morogoro/

https://www.jamhurimedia.co.tz/bodi-ya-kahawa-yaja-na-mgahawa-unaotembea/

https://www.jamhurimedia.co.tz/tra-yawaita-wananchi-kutembelea-banda-lao-maonesho-nanenane/

https://www.jamhurimedia.co.tz/nkuba-apinga-ushindi-wa-mgombea-tls/

https://www.jamhurimedia.co.tz/majenerali-6-waagwa-rasmi-jwtz/

https://www.jamhurimedia.co.tz/haniyeh-wa-hamas-kuzikwa-leo-qatar/

https://www.jamhurimedia.co.tz/rais-samia-azindua-hospitali-ya-wilaya-ya-gairo/

https://www.jamhurimedia.co.tz/rais-samia-kuanza-ziara-morogoro-leo/

https://www.jamhurimedia.co.tz/aziz-ki-abeba-tuzo-nne/

https://www.jamhurimedia.co.tz/simba-yamtambulisha-mlinda-mlango-mpya/

https://www.jamhurimedia.co.tz/dk-biteko-afunga-maonesho-ya-nanenane-nyanja-za-juu-kusini/

https://www.jamhurimedia.co.tz/rais-samia-sgr-siyo-ndoto-tena/

https://www.jamhurimedia.co.tz/wahuni-washambulia-faiba-tena-ufaransa/

https://www.jamhurimedia.co.tz/iran-yaapa-kulipiza-kisasi-kufuatia-mauaji-ya-kiongozi-wa-kisiasa-wa-hamas-haniyeh/

https://www.jamhurimedia.co.tz/waziri-mkuu-ahani-msiba-wa-mama-yake-mzazi-halima-mdee/

https://www.jamhurimedia.co.tz/rais-samia-ateua-kamati-ya-kutathmini-na-kushauri-masuala-ya-kodi/

https://www.jamhurimedia.co.tz/rais-samia-amuapisha-cgp-katundu/

https://www.jamhurimedia.co.tz/mlongazila-kupandikiza-meno-bandia/

https://www.jamhurimedia.co.tz/rais-dk-samia-atoa-tuzo-ya-mkapa-kwa-washindi-sekta-ya-afya/

https://www.jamhurimedia.co.tz/tanzania-morocco-zafurahia-uhusiano/

https://www.jamhurimedia.co.tz/drc-congo-na-rwanda-kumaliza-mapigano/

https://www.jamhurimedia.co.tz/takukuru-kuchunguza-miradi-ya-bil-34-tanga/

https://www.jamhurimedia.co.tz/rais-samia-ashiriki-kumbukizi-ya-3-ya-urithi-wa-mkapa-jnicc-jijini-dar-es-salaam/

https://www.jamhurimedia.co.tz/serikali-yahitimisha-kwa-mafanikio-zoezi-la-utoaji-elimu-ya-fedha-mtwara/

https://www.jamhurimedia.co.tz/rais-dk-mwinyi-kushiriki-uzinduzi-wa-sgr/

https://www.jamhurimedia.co.tz/serikali-kutatua-mgogoro-wa-ardhi-ngara/

https://www.jamhurimedia.co.tz/wakili-mtatiro-na-ally-kileo-wataja-sifa-za-rais-ajaye-wa-tls/

https://www.jamhurimedia.co.tz/ismail-haniyeh-alikuwa-nani/

https://www.jamhurimedia.co.tz/kiongozi-wa-hamas-ismail-haniyeh-auawa/

https://www.jamhurimedia.co.tz/trc-yaomba-radhi-kwa-hitilafu-ya-umeme-kwenye-reli-ya-sgr-kilosa-kidete/

https://www.jamhurimedia.co.tz/meli-ya-mizigo-kutoka-china-yatia-nanga-bandari-ya-tanga/

https://www.jamhurimedia.co.tz/rais-samia-kuzindua-rasmi-reli-ya-mwendo-kasi-dar-dodoma/

https://www.jamhurimedia.co.tz/dk-biteko-awakemea-watumishi-wanaokwamisha-wafanyabiashara/

https://www.jamhurimedia.co.tz/act-wazalendo-wimbi-la-uporaji-na-migogoro-ya-ardhi-tunasimama-na-wananchi/

https://www.jamhurimedia.co.tz/watanzania-wangaara-tuzo-za-kimataifa/

https://www.jamhurimedia.co.tz/mama-mzazi-wa-halima-mdee-afariki/

https://www.jamhurimedia.co.tz/waziri-jerry-silaa-atembelea-tcra-dar/

https://www.jamhurimedia.co.tz/serikali-yaombwa-kutambua-mbegu-asili/

https://www.jamhurimedia.co.tz/hatua-hii-ya-heslb-kutoa-mafunzo-ya-tehama-ni-ya-kupongezwa/

https://www.jamhurimedia.co.tz/waziri-kijaji-abainisha-mikakati-ya-mazingira/

https://www.jamhurimedia.co.tz/zungu-mgeni-rasmi-mahafali-ya-tisa-chuo-cha-furahika/

https://www.jamhurimedia.co.tz/marekani-kuipa-ukraine-msaada-wa-kijeshi-wa-dola-bilioni-1-7/

https://www.jamhurimedia.co.tz/vikosi-vya-usalama-vyadhibiti-maandamano-venezuela/

https://www.jamhurimedia.co.tz/kisarawe-kunogile-yaja-na-bata-msituni-festival-ndani-ya-msitu-wa-kazimzumbwi/

https://www.jamhurimedia.co.tz/jenerali-mkunda-afungua-mazoezi-ya-medani-umoja-2024-aishukuru-serikali-ya-tanzania-china/

https://www.jamhurimedia.co.tz/jkci-dar-group-yazindua-mtambo-wa-kisasa-wa-oksijeni/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-la-julai-30-agosti-5-2024/

https://www.jamhurimedia.co.tz/rais-samia-aridhia-ombi-la-kinana-kujiuzulu/

https://www.jamhurimedia.co.tz/rais-samia-atoa-wito-kwa-wadau-sekta-binafsi-kushirikiana-na-serikali/

https://www.jamhurimedia.co.tz/rais-samia-ampandisha-cheo-kamishna-wa-magereza/

https://www.jamhurimedia.co.tz/mradi-wa-taza-kuunganisha-umeme-afrika/

https://www.jamhurimedia.co.tz/mawaziri-wa-israel-waidhinisha-ulipizaji-kisasi-wa-netanyahu-dhidi-ya-hezbollah/

https://www.jamhurimedia.co.tz/kim-ashiriki-uokozi-waathirika-wa-mafuriko/

https://www.jamhurimedia.co.tz/yanga-kucheza-na-red-arrows-siku-ya-wananchi/

https://www.jamhurimedia.co.tz/haji-manara-atangaza-vita-na-ali-kamwe/

https://www.jamhurimedia.co.tz/mwanamuziki-snura-aacha-na-muziki-amrudia-mungu/

https://www.jamhurimedia.co.tz/zaidi-ya-bilioni-23-kutumika-kusambaza-umeme-kilimanjaro-vijijini/

https://www.jamhurimedia.co.tz/rais-dkt-samia-aongoza-mkutano-wa-15-wa-baraza-la-taifa-la-biashara-ikulu-dar/

https://www.jamhurimedia.co.tz/rais-wa-zamani-wa-afrika-kusini-jacob-zuma-afukuzwa-anc/

https://www.jamhurimedia.co.tz/ukraine-yaendelea-kuyalenga-maeneo-ya-urusi/

https://www.jamhurimedia.co.tz/utekelezaji-mradi-ujenzi-wa-miundombinu-ya-barabara-njombe-wafikia-asilimia-88-3-injinia-ruth/

https://www.jamhurimedia.co.tz/mhasibu-wa-halmashauri-mbarali-atiwa-hatiani/

https://www.jamhurimedia.co.tz/urus-tanzania-kupeleka-teknolojia-ya-uhimilishaji-mifugo-kutoka-marekani-brazil-maonesho-ya-nanenane/

https://www.jamhurimedia.co.tz/trc-korea-kushirikiana-sgr/

https://www.jamhurimedia.co.tz/afya-kwa-vijana-ilivyopunguza-magonjwa-ya-ngono-morogoro/

https://www.jamhurimedia.co.tz/biteko-mgeni-rasmi-uzinduzi-sera-ya-taifa-biashara-2003-toleo-la-2023/

https://www.jamhurimedia.co.tz/serikali-haikubaliani-na-vitendo-viovu-dhidi-ya-watoto-masauni/

https://www.jamhurimedia.co.tz/wananachi-mtakanini-wilayani-namtumbo-waipa-tano-serikali-kuwasogezea-huduma-za-kibingwa-za-afya/

https://www.jamhurimedia.co.tz/mgombea-urais-tls-nkuba-ajipanga-kuleta-mabadiliko-ndani-ya-chama-endapo-atachaguliwa/

https://www.jamhurimedia.co.tz/akatwa-kiganja-cha-mkono-kwa-wivu-wa-mapenzi/

https://www.jamhurimedia.co.tz/rais-samia-asisitiza-umuhimu-wa-uhuru-wa-habari/

https://www.jamhurimedia.co.tz/majaliwa-achangisha-milioni-900-ujenzi-wa-kanisa-kuu-lindi/

https://www.jamhurimedia.co.tz/mahakama-yamwachia-huru-aliyekuwa-ded-mafia/

https://www.jamhurimedia.co.tz/biteko-ataka-huduma-bora-kwa-wananchi/

https://www.jamhurimedia.co.tz/serikali-kuendelea-kukiunga-mkono-chuo-cha-ndc/

https://www.jamhurimedia.co.tz/pwani-yapata-wauguzi-120-kukabiliana-changamoto-ya-upungufu-wa-wauguzi/

https://www.jamhurimedia.co.tz/dk-shukia-dira-ya-taifa-ya-maendeleo-ni-mali-ya-wananchi/

https://www.jamhurimedia.co.tz/tanzania-mwenyeji-kongamano-umoja-wa-mataifa-la-utalii-wa-vyakula-vya-asili-afrika/

https://www.jamhurimedia.co.tz/bonanza-la-wizara-ya-nishati-lapamba-moto-dodoma/

https://www.jamhurimedia.co.tz/un-yaonya-kuwa-binadamu-wanaathrika-na-janga-la-joto-kali/

https://www.jamhurimedia.co.tz/obama-amuunga-mkono-kamala-harris-kuwa-rais/

https://www.jamhurimedia.co.tz/serikali-yaombwa-kuwawezesha-wakulima-vijijini/

https://www.jamhurimedia.co.tz/iraq-roketi-zafyatuliwa-kuelekea-kambi-ya-jeshi-la-marekani/

https://www.jamhurimedia.co.tz/wazazi-nchini-watakiwa-kuwalinda-watoto-na-kuwapa-lishe-bora/

https://www.jamhurimedia.co.tz/viongozi-wa-halmashauri-watakiwa-kusimamia-miradi-kwa-weledi/

https://www.jamhurimedia.co.tz/ccm-njombe-rc-mtaka-waridhishwa-na-ujenzi-barabara-ya-kiwango-cha-zege-itoli-ludewa-manda/

https://www.jamhurimedia.co.tz/bashungwa-tumejipanga-kuifungua-dar-es-salaam/

https://www.jamhurimedia.co.tz/shahidi-aeleza-mume-wake-alivyopigwa-na-nathwani-mpaka-kuzimia/

https://www.jamhurimedia.co.tz/tanzania-yahimiza-nchi-zipate-mikopo-nafuu/

https://www.jamhurimedia.co.tz/vyuo-vikuu-15-nje-ya-nchi-kufanya-maonyesho-arusha/

https://www.jamhurimedia.co.tz/utasa-unavyogeuka-laana-kwa-wanawake/

https://www.jamhurimedia.co.tz/samia-kusafiri-kwa-sgr-dar-dodoma/

https://www.jamhurimedia.co.tz/tanzania-kuwa-mwenyeji-mkutano-wa-kimataifa-wa-barabara/

https://www.jamhurimedia.co.tz/msadara-wa-wachezaji-wawasili-paris-kushiriki-olympic/

https://www.jamhurimedia.co.tz/meli-yenye-bendera-ya-tanzania-yazama-taiwan/

https://www.jamhurimedia.co.tz/meli-za-kivita-kutoka-china-zawasilia-nchini-kuadhimisha-miaka-60-ya-jwtz/

https://www.jamhurimedia.co.tz/ruto-ateua-vigogo-wa-upinzani-kuwa-mawaziri/

https://www.jamhurimedia.co.tz/kadi-za-nec-kutumika-chaguzi-zijazo/

https://www.jamhurimedia.co.tz/tawa-yatoa-madawati-shule-ya-msingi-changarawe-mvomero/

https://www.jamhurimedia.co.tz/waziri-kairuki-aongoza-ujumbe-wa-tanzania-kushiriki-mkutano-wa-pili-wa-shirika-la-utalii-duniani/

https://www.jamhurimedia.co.tz/mitungi-ya-gesi-ya-bil-10-kutolewa-na-serikali-2024-25-kapinga/

https://www.jamhurimedia.co.tz/diwani-kimwanga-awataka-wazazi-kupuuza-taarifa-za-kutekwa-kwa-watoto/

https://www.jamhurimedia.co.tz/who-ina-wasiwasi-wa-kuzuka-mripuko-wa-ugonjwa-wa-polio-gaza/

https://www.jamhurimedia.co.tz/democratic-waonekana-kumuunga-mkono-harris/

https://www.jamhurimedia.co.tz/dira-mpya-itafsiri-maono-ya-rais-samia/

https://www.jamhurimedia.co.tz/basata-yamfungia-babu-wa-tiktok/

https://www.jamhurimedia.co.tz/rais-samia-atengua-euzi-wa-viongozi-mba/

https://www.jamhurimedia.co.tz/ziara-ya-dk-biteko-bukombe-yawakosha-wakazi/

https://www.jamhurimedia.co.tz/tef-epukeni-kusambaza-taarifa-za-uongo-za-watoto-kutekwa/

https://www.jamhurimedia.co.tz/rais-samia-ana-maamuzi-magumu/

https://www.jamhurimedia.co.tz/nida-vitambulisho-vilivyofutika-maandishi-virejeshwe/

https://www.jamhurimedia.co.tz/naibu-waziri-kapinga-chagueni-viongozi-watakaowaletea-maendeleo-na-kutatua-kero-zenu/

https://www.jamhurimedia.co.tz/samia-kugharamia-tiba-mtoto-aliyenusurika-kuchinjwa/

https://www.jamhurimedia.co.tz/mifugo-wizi-waathiri-ujenzi-kiwanja-cha-ndege-msalato/

https://www.jamhurimedia.co.tz/gazeti-la-jamhuri-julai-23-29-2024/

https://www.jamhurimedia.co.tz/mradi-wa-bil-60-umwagiliaji-kunufaisha-wakulima/

https://www.jamhurimedia.co.tz/tanzania-yaunga-mkono-agenda-za-shirika-la-utalii-duniani-za-uwekezaji-wa-kimkakati-na-usalama/

https://www.jamhurimedia.co.tz/vijiji-vyote-nyasa-vyafikiwa-na-umeme/

https://www.jamhurimedia.co.tz/dc-magiti-ampigia-simu-aweso-tatizo-la-maji-majumba-sita/

https://www.jamhurimedia.co.tz/mwigulu-hakuna-uchotaji-fedha-bot/

https://www.jamhurimedia.co.tz/68876-2/

https://www.jamhurimedia.co.tz/bukombe-waishuku-serikali-kwa-maendeleo/

https://www.jamhurimedia.co.tz/uchaguzi-wa-marekani-2024-trump-sasa-ndiye-mteule/

https://www.jamhurimedia.co.tz/waziri-bashe-akabidhi-mradi-wa-umwagiliaji-luiche-kigoma/

https://www.jamhurimedia.co.tz/bashe-rais-samia-hataki-utani-kilimo-cha-umwagiliaji/

https://www.jamhurimedia.co.tz/waziri-kairuki-kushiriki-mkutano-wa-67-wa-mawaziri-wa-shirika-la-umoja-wa-mataifa-la-utalii-duniani-zambia/

https://www.jamhurimedia.co.tz/mbunge-wa-kuteuliwa-mbarouk-nassor-ajiuzulu/

https://www.jamhurimedia.co.tz/meli-vita-ya-kichina-ya-matibabu-yahudumu-watu-zaidi-ya-5000/

https://www.jamhurimedia.co.tz/biden-ajitoa-kwenye-kinyanganyiro-cha-urais-marekani/

https://www.jamhurimedia.co.tz/kailima-wengi-wajitokeza-kuboresha-kujiandikisha-daftari-la-kudumua-la-wapigakura/

https://www.jamhurimedia.co.tz/rais-samia-ateuanape-makamba-kupangiwa-majukumu-mengine/

https://www.jamhurimedia.co.tz/dira-ya-taifa-ya-maendeleo-ni-picha-maono/

https://www.jamhurimedia.co.tz/afrika-mashariki-kukabiliwa-na-malaria-sugu/

https://www.jamhurimedia.co.tz/wapiga-kura-wapya-zaidi-ya-milioni-tano-kuandikishwa/

https://www.jamhurimedia.co.tz/katibu-tawala-songea-atoa-maagizo-kwa-kwa-viongozi-wa-vijiji-kata/

https://www.jamhurimedia.co.tz/serikali-yajipanga-usambazaji-umeme-kwa-kuweka-mazingira-wezeshi-mbinga/

https://www.jamhurimedia.co.tz/rais-ataka-viongozi-wa-kimila-kujijengea-mvuto-wa-kuaminiwa-na-jamii/

https://www.jamhurimedia.co.tz/magaeuzi-yalinusuru-shirika-la-posta-tanzania/

https://www.jamhurimedia.co.tz/waziri-bashe-atangaza-neema-kilimo-cha-umwagiliaji-katavi/

https://www.jamhurimedia.co.tz/waadhimisha-siku-ya-nelson-mandela-dar/

https://www.jamhurimedia.co.tz/trump-aridhia-kuwa-mgombea-urais-wa-republican/

https://www.jamhurimedia.co.tz/pinda-atoa-zawadi-kwa-walimu-kavuu/

https://www.jamhurimedia.co.tz/tathimini-ujenzi-wa-barabara-kwa-kutumia-teknolojia-ya-kisasa-ya-ecoroads-yaleta-matumaini/

https://www.jamhurimedia.co.tz/global-education-link-yadahili-wanafunzi-maonyesho-ya-vyuo-vikuu-zanzibar-2/

https://www.jamhurimedia.co.tz/dulla-makabila-linex-wapamba-tamasha-la-uboreshaji-wa-daftari-la-kudumu-la-wapiga-kura/

https://www.jamhurimedia.co.tz/nmb-yawapiga-msasa-wanahabari-masuala-ya-bima/

https://www.jamhurimedia.co.tz/mabomu-baridi-700-kutumika-nachingwea-kudhibiti-tembo/

https://www.jamhurimedia.co.tz/viswaswadu-kutumika-kuboresha-daftari-la-kudumu-la-wapiga-kura/

https://www.jamhurimedia.co.tz/global-education-link-yadahili-wanafunzi-maonyesho-ya-vyuo-vikuu-zanzibar/

https://www.jamhurimedia.co.tz/nape-msinunue-vocha-tofauti-na-bei-iliyoelekezwa/

https://www.jamhurimedia.co.tz/rais-samia-azungumza-na-wananchi-mbozi-mkoani-songwe/

https://www.jamhurimedia.co.tz/watuhumiwa-179-mwanza-wadakwa-kwa-makosa-mbalimbali/

https://www.jamhurimedia.co.tz/mwenge-wa-uhuru-yaifikia-miradi-14-ya-zaidi-ya-thamani-bil-3-3-kiteto/

https://www.jamhurimedia.co.tz/rais-mwinyi-akutana-na-balozi-wa-uswisi-nchini-tanzania-ikulu-zanzibar/

https://www.jamhurimedia.co.tz/rais-biden-asitisha-kampeni-baada-ya-kugundulika-na-uviko/

https://www.jamhurimedia.co.tz/anaswa-na-mbinu-mpya-ya-utengenezaji-dawa-za-kulevya-kwa-kutumia-tiba-asili/

https://www.jamhurimedia.co.tz/makubaliano-ya-kuweka-chini-silaha-drc-yarefushwa-siku-15/

https://www.jamhurimedia.co.tz/msimamizi-wa-mirathi-ajirithisha-magari/

https://www.jamhurimedia.co.tz/rais-samia-bei-ya-mahindi-sasa-700-mbegu-za-ruzuku-kuanza-mwenzi-ujao/

https://www.jamhurimedia.co.tz/aisha-masaka-atua-ligi-kuu-wanawake-england/

https://www.jamhurimedia.co.tz/vigogo-act-wazalendo-kuzunguka-majimbo-125/

https://www.jamhurimedia.co.tz/jukumu-letu-kuzingatia-sheria-katika-kutoa-na-kupokea-huduma-simbachawane/

https://www.jamhurimedia.co.tz/dkt-samia-azungumza-na-wananchi-wa-laela-mkoani-rukwa/

https://www.jamhurimedia.co.tz/mkuu-wa-majeshi-ya-ulinzi-jenerali-mkunda-apokea-ujumbe-wa-jeshi-la-china/

https://www.jamhurimedia.co.tz/wanasayansi-wagundua-pango-la-makazi-mwezini/

https://www.jamhurimedia.co.tz/auawa-katika-maandamano-ya-kumtaka-rais-wa-kenya-kuondoka-madarakani/

https://www.jamhurimedia.co.tz/mahakama-yaamuru-hersi-na-wenzake-wangoke-yanga/

https://www.jamhurimedia.co.tz/chalamila-apokea-melivita-ya-matibabu-ya-jeshi-la-ukombozi-la-watu-wa-china-matibabu-bure/

https://www.jamhurimedia.co.tz/atcl-yaanzisha-kampeni-ya-afya-yako-mtaji-wako/

https://www.jamhurimedia.co.tz/babati-dc-haijakurupuka-bali-imejipanga-na-miradi-yenye-viwango-mnzava/

https://www.jamhurimedia.co.tz/rpc-mtatiro-azindua-kampeni-ya-usambazaji-nishati-ya-kupikia-nchini-kati-ya-g4s-na-oryx-gas/

https://www.jamhurimedia.co.tz/rais-samia-afungua-jengo-la-utawala-la-halmashauri-ya-wilaya-ya-kalambo-rukwa/

https://www.jamhurimedia.co.tz/matembezi-ya-utulivu-rasmi-kufanyika-julai-20/

https://www.jamhurimedia.co.tz/rais-samia-afungua-barabara-ya-sumbawanga-matai-kasanga-rukwa/

https://www.jamhurimedia.co.tz/trump-amchagua-jd-vance-kama-mgombea-mwenza-wake/

https://www.jamhurimedia.co.tz/pandu-aiomba-serikali-kuligawa-jimbo-la-namtumbo-ili-kurahisisha-upatikanaji-huduma/

https://www.jamhurimedia.co.tz/muuaji-wa-wanawake-42-kenya-akamatwa-akiwa-klabu/

https://www.jamhurimedia.co.tz/maandamano-yarejea-tena-kudai-uwajibikaji-kenya/

https://www.jamhurimedia.co.tz/rais-kagame-ashinda-kwa-kishindo-matokeo-ya-awali-uchaguzi-rwanda/

https://www.jamhurimedia.co.tz/rais-wa-shirikisho-la-soka-colombia-mtoto-wake-wakamatwa/

https://www.jamhurimedia.co.tz/mtu-tajiri-zaidi-barani-afrika-asema-hana-nyumba-nje-ya-nigeria/

https://www.jamhurimedia.co.tz/polisi-200-zaidi-wa-kenya-waelekea-haiti/

https://www.jamhurimedia.co.tz/arusha-yaibuka-kinara-katika-raundi-ya-tatu-ya-mashindano-ya-gofu-ya-lina-pg-tour/

https://www.jamhurimedia.co.tz/mwenyekiti-bawacha-mara-akemea-rushwa-ndani-ya-chama/

https://www.jamhurimedia.co.tz/kaya-400000-kuondolewa-tasaf-baada-ya-kuboreka-kimaisha/

https://www.jamhurimedia.co.tz/utendechole-kunufaika-mradi-wa-umeme-utakaopitisha-nyaya-chini-ya-bahari/

https://www.jamhurimedia.co.tz/trump-akaribishwa-kwa-nderemo-kongamano-la-chama-cha-republican/

https://www.jamhurimedia.co.tz/wasiotimiza-vigezo-vya-uwanja-bora-wawekeni-pembeni/

https://www.jamhurimedia.co.tz/soma-gazeti-la-jamhuri-julai-16-22-2024/

https://www.jamhurimedia.co.tz/mikataba-minne-ya-bilioni-10-75-yasainiwa-kujenga-miundombinu-ya-barabara-dar/

https://www.jamhurimedia.co.tz/mitaji-changamoto-ya-vijana-kwenye-kilimo-waziri-bashe/

https://www.jamhurimedia.co.tz/rais-samia-ahitimisha-ziara-yake-katavi/

https://www.jamhurimedia.co.tz/tanesco-kuanza-kufanya-maboresho-ya-luku-pwani-na-dar/

https://www.jamhurimedia.co.tz/ppra-yataja-siri-ya-kupata-tuzo-ya-mshindi-wa-kwanza-katika-kipengele-cha-mamlaka-za-udhibiti/

https://www.jamhurimedia.co.tz/udom-yaibuka-mshindi-wa-kwanza-kipengele-cha-taasisi-za-elimu-ya-juu-katika-sabasaba/

https://www.jamhurimedia.co.tz/katavi-kuwa-kanda-ya-ununuzi-wa-mazao/

https://www.jamhurimedia.co.tz/biden-ataka-wamarekani-watulize-joto-la-kisiasa/

https://www.jamhurimedia.co.tz/miili-ya-watu-8-yagunduliwa-kwenye-dampo-la-takataka-nairobi/

https://www.jamhurimedia.co.tz/kanisa-katoliki-lalaani-shambulio-dhidi-ya-trump/

https://www.jamhurimedia.co.tz/nirc-yawataka-wakandarasi-kusaidia-jamii-maeneo-yenye-miradi/

https://www.jamhurimedia.co.tz/dc-chunguza-malalamiko-ya-wajawazito-dkt-mpango/

https://www.jamhurimedia.co.tz/kisarawe-yaita-maabara-kutoa-elimu-ya-ufugaji/

https://www.jamhurimedia.co.tz/rais-mwinyi-azitaka-taasisi-za-biashara-kuondoa-urasimu/

https://www.jamhurimedia.co.tz/viongozi-wa-dunia-walaani-shambulio-dhidi-ya-trump/

https://www.jamhurimedia.co.tz/tunaondoka-mbulu-dc-tukiwa-tumeridhika-kabisa-ya-kwamba-mmemtendea-haki-dkt-samia-na-hata-sisi-pia/

https://www.jamhurimedia.co.tz/rais-dkt-samia-akizindua-maghala-na-vihenge-vya-kisasa-vya-kuhifadhia-nafaka-vya-nfra-katavi/

https://www.jamhurimedia.co.tz/serikali-kutekeleza-mapendekezo-ya-tume-ya-kuboresha-mifumo-ya-haki-jinai/

https://www.jamhurimedia.co.tz/polisi-wachunguzwa-kuhusu-miili-iliyotupwa-kenya/

https://www.jamhurimedia.co.tz/semfuko-awahimiza-watanzania-kuchangamkia-fursa-ya-ufugaji-wa-wanyamapori/

https://www.jamhurimedia.co.tz/michakato-ya-miradi-ya-maendeleo-iharakishwe/

https://www.jamhurimedia.co.tz/wafungwa-na-walinzi-wauawa-katika-gereza-la-mogadishu/

https://www.jamhurimedia.co.tz/watu-71-wauawa-baada-ya-shambulizi-la-israel-gaza/

https://www.jamhurimedia.co.tz/viongozi-wanne-hatiani-kwa-ubadhirifu-fedha-za-urasimishaji-makazi/

https://www.jamhurimedia.co.tz/gavana-bwanku-awashauri-waganga-wa-jadi-kujiepusha-na-ramli-chonganishi/

https://www.jamhurimedia.co.tz/rais-samia-awapa-tano-wakulima-nchini-kwa-uzalishaji-chakula-nchini-nchi-ina-akiba-ya-kutosha/

https://www.jamhurimedia.co.tz/rais-samia-apokea-taarifa-ya-kituo-cha-kupoza-umeme-wa-gridi-ya-taifa-katavi-azungumza-na-wananchi-mlele/

https://www.jamhurimedia.co.tz/rc-chalamila-serikali-itaweka-utaratibu-mzuri-kwa-wafanyabiashara-simu-2000/

https://www.jamhurimedia.co.tz/rais-samia-acheni-kuvamia-maeneo-ya-hifadhi/

https://www.jamhurimedia.co.tz/timu-ya-taifa-ya-tenis-safarini-kushiriki-mashindano-ya-dunia/

https://www.jamhurimedia.co.tz/ega-yatoa-wito-kwa-wananchi-kutumia-mfumo-wa-e-mrejesho/

https://www.jamhurimedia.co.tz/wadau-wa-masuala-ya-kidigitali-waomba-kutambulika-kama-wafanyabiashara/

https://www.jamhurimedia.co.tz/crdb-yazidi-kuwainua-wanawake-kiuchumi-yaweka-akaunti-maalumu-ya-malkia/

https://www.jamhurimedia.co.tz/pura-asilimia-80-ya-watanzania-kutumia-nishati-safi-ya-kupikia-ifikapo-2034/

https://www.jamhurimedia.co.tz/watu-zaidi-ya-200-waunganishiwa-huduma-ya-faiba-mlangoni-katika-maonesho-sabasaba/

https://www.jamhurimedia.co.tz/tume-ya-madini-yatahadharisha-waombaji-leseni/

https://www.jamhurimedia.co.tz/ayubu-rioba-vyombo-vya-habari-vya-afrika-shirikianeni-na-kubadilishana-maudhui/

https://www.jamhurimedia.co.tz/tef-yalaani-kitendo-cha-walimu-kumshambuliwa-mwandishi-wa-habari-wa-guardian/

https://www.jamhurimedia.co.tz/cbe-yajivunia-kuanzisha-masters-kwa-njia-ya-mtandaoni/

https://www.jamhurimedia.co.tz/pura-yajipanga-kuongeza-wawekezaji/

https://www.jamhurimedia.co.tz/watuhumiwa-kesi-ya-mauaji-mtoto-albino-waangua-kilio-mahakamani/

https://www.jamhurimedia.co.tz/matumizi-ya-umeme-jua-kwa-wakulima-yatawapunguzia-gharama-wengi-hawafahamu/

https://www.jamhurimedia.co.tz/shehe-asimamishwa-kazi-kwa-kufungisha-ndoa-feki/

https://www.jamhurimedia.co.tz/makamba-aongoza-ujumbe-wa-tanzania-mkutano-wa-kamati-ya-mawaziri-wa-asasi-ya-siasa-ulinzi-na-usalama-sadc/

https://www.jamhurimedia.co.tz/unep-kuleta-neema-tanzania/

https://www.jamhurimedia.co.tz/urusi-kupeleka-silaha-ujerumani-kutachochea-vita-baridi/

https://www.jamhurimedia.co.tz/msd-yaanika-mikakati-ya-kujiongezea-mapato/

https://www.jamhurimedia.co.tz/wema-sepetu-ipo-haja-ya-wasanii-kurudi-shule-wampa-tano-rais-samia/

https://www.jamhurimedia.co.tz/who-homa-ya-nyani-bado-ni-tishio-la-kiafya-ulimwenguni/

https://www.jamhurimedia.co.tz/rais-ruto-avunja-baraza-lake-la-mawaziri/

https://www.jamhurimedia.co.tz/nit-awataka-vijana-kuchangamkia-fursa-masomo-ya-kimkakati/

https://www.jamhurimedia.co.tz/rais-samia-ateua-na-kumuapisha-mkurugenzi-mkuu-wa-idara-ya-usalama-wa-taifa/

https://www.jamhurimedia.co.tz/wakala-wa-forodha-mbaroni-kwa-tuhuma-kumuua-rafiki-yake-na-kumuibia-milioni-61/

https://www.jamhurimedia.co.tz/tume-ya-madini-kuboresha-vifungashio-vya-madini-ili-kudhibiti-utoroshaji/

https://www.jamhurimedia.co.tz/pinda-amrejeshea-nyumba-bibi-aliyoihangaikia-kwa-zaidi-ya-miaka-10-kigoma/

https://www.jamhurimedia.co.tz/udsm-oslo-ilivyodhamiria-kupunguza-mtanziko-katika-utoaji-huduma-za-afya-nchini/

https://www.jamhurimedia.co.tz/mashindano-ya-gofu-ya-kumuenzi-lina-nkya-kuendelea-leo-arusha/

https://www.jamhurimedia.co.tz/udom-yawakaribisha-wadau-kushirikiana-kutengeneza-tiba-lishe/

https://www.jamhurimedia.co.tz/dkt-mpango-asisitiza-elimu-kuepuka-maradhi/

https://www.jamhurimedia.co.tz/jela-miaka-sita-kwa-kumtukana-rais-wa-uganda/

https://www.jamhurimedia.co.tz/rais-wa-sudan-kusini-amfukuza-kazi-waziri-wa-fedha/

https://www.jamhurimedia.co.tz/bandari-bubu-zatajwa-mihadarati-kuingia-zbar/

https://www.jamhurimedia.co.tz/act-wazalendo-wataka-kiswahili-iwe-lugha-ya-kufundishia/

https://www.jamhurimedia.co.tz/ubalozi-wa-ufaransa-kuadhimisha-leo-sikukuu-ya-julai-14/
"""

direct_URLs = text.split('\n')
direct_URLs = [i for i in direct_URLs if "https://www.jamhurimedia.co.tz" in i]

source = 'jamhurimedia.co.tz'

hdr = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}


final_result = list(set(direct_URLs))   
print('Total number of urls found: ', len(final_result))



url_count = 0
processed_url_count = 0

for url in final_result:
    if url:
        print(url, "FINE")
        ## SCRAPING USING NEWSPLEASE:
        try:
            #header = {'User-Agent': ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36''(KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36')}

            response = requests.get(url, headers=hdr)
            # process
            soup = BeautifulSoup(response.content)

            article = NewsPlease.from_html(response.text, url=url).__dict__

            # add on some extras
            article['date_download']=datetime.now()
            article['download_via'] = "Direct2"
            article['source_domain'] = source
            article['language'] = 'sw'
            # title has no problem
            # print(soup)
          
            print("newsplease title: ", article['title'])

            if not article['maintext']:
                try:
                    article['maintext'] = soup.find('div', {'class' : 'post-content'}).text.strip()
                    
                except:
                    maintext = ''
                    for i in soup.find('div', {'class' : 'post-content'}).find_all('p'):
                        try:
                            maintext += i.text
                        except:
                            pass
                    article['maintext'] =  maintext.strip()
            if "Na " in  article['maintext'][:4]:
                article['maintext'] = "\n".join(article['maintext'].split('\n')[1:])
                
            if article['maintext']:
                print("newsplease maintext: ", article['maintext'][:50])
            
            try:
                date = soup.find('div', {'class' : 'post-date'}).text
                article['date_publish'] = dateparser.parse(date)
            except:
                article['date_publish'] =article['date_publish'] 
            print("newsplease date: ",  article['date_publish'])



            try:
                year = article['date_publish'].year
                month = article['date_publish'].month
                colname = f'articles-{year}-{month}'
                
            except:
                colname = 'articles-nodate'
            
            # Inserting article into the db:
            try:
                db[colname].insert_one(article)
                # count:
                if colname != 'articles-nodate':
                    url_count = url_count + 1
                    print("Inserted! in ", colname, " - number of urls so far: ", url_count)
                db['urls'].insert_one({'url': article['url']})
            except DuplicateKeyError:
                pass
                print("DUPLICATE! Not inserted.")
                    
        except Exception as err: 
            print("ERRORRRR......", err)
            pass
        processed_url_count += 1
        print('\n',processed_url_count, '/', len(final_result), 'articles have been processed ...\n')

    else:
        pass

print("Done inserting ", url_count, " manually collected urls from ",  source, " into the db.")
